
package com.frojasg1.nchf5g.superpojo.model;

public enum SMServiceType {
    CONTENT_PROCESSING,
    FORWARDING,
    FORWARDING_MULTIPLE_SUBSCRIPTIONS,
    FILTERING,
    RECEIPT,
    NETWORK_STORAGE,
    TO_MULTIPLE_DESTINATIONS,
    VIRTUAL_PRIVATE_NETWORK_VPN_,
    AUTO_REPLY,
    PERSONAL_SIGNATURE,
    DEFERRED_DELIVERY;
}
