/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ChargingDataResponse
 */
@JsonPropertyOrder({
  ChargingDataResponse.JSON_PROPERTY_INVOCATION_TIME_STAMP,
  ChargingDataResponse.JSON_PROPERTY_INVOCATION_SEQUENCE_NUMBER,
  ChargingDataResponse.JSON_PROPERTY_INVOCATION_RESULT,
  ChargingDataResponse.JSON_PROPERTY_SESSION_FAILOVER,
  ChargingDataResponse.JSON_PROPERTY_MULTIPLE_UNIT_INFORMATION,
  ChargingDataResponse.JSON_PROPERTY_TRIGGERS,
  ChargingDataResponse.JSON_PROPERTY_P_D_U_SESSION_CHARGING_INFORMATION,
  ChargingDataResponse.JSON_PROPERTY_ROAMING_Q_B_C_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class ChargingDataResponse   {
  public static final String JSON_PROPERTY_INVOCATION_TIME_STAMP = "invocationTimeStamp";
  @JsonProperty(JSON_PROPERTY_INVOCATION_TIME_STAMP)
  private Date invocationTimeStamp;

  public static final String JSON_PROPERTY_INVOCATION_SEQUENCE_NUMBER = "invocationSequenceNumber";
  @JsonProperty(JSON_PROPERTY_INVOCATION_SEQUENCE_NUMBER)
  private Integer invocationSequenceNumber;

  public static final String JSON_PROPERTY_INVOCATION_RESULT = "invocationResult";
  @JsonProperty(JSON_PROPERTY_INVOCATION_RESULT)
  private InvocationResult invocationResult;

  public static final String JSON_PROPERTY_SESSION_FAILOVER = "sessionFailover";
  @JsonProperty(JSON_PROPERTY_SESSION_FAILOVER)
  private SessionFailover sessionFailover;

  public static final String JSON_PROPERTY_MULTIPLE_UNIT_INFORMATION = "multipleUnitInformation";
  @JsonProperty(JSON_PROPERTY_MULTIPLE_UNIT_INFORMATION)
  private List<@Valid MultipleUnitInformation> multipleUnitInformation;

  public static final String JSON_PROPERTY_TRIGGERS = "triggers";
  @JsonProperty(JSON_PROPERTY_TRIGGERS)
  private List<@Valid Trigger> triggers;

  public static final String JSON_PROPERTY_P_D_U_SESSION_CHARGING_INFORMATION = "pDUSessionChargingInformation";
  @JsonProperty(JSON_PROPERTY_P_D_U_SESSION_CHARGING_INFORMATION)
  private PDUSessionChargingInformation pDUSessionChargingInformation;

  public static final String JSON_PROPERTY_ROAMING_Q_B_C_INFORMATION = "roamingQBCInformation";
  @JsonProperty(JSON_PROPERTY_ROAMING_Q_B_C_INFORMATION)
  private RoamingQBCInformation roamingQBCInformation;

  public ChargingDataResponse invocationTimeStamp(Date invocationTimeStamp) {
    this.invocationTimeStamp = invocationTimeStamp;
    return this;
  }

  /**
   * Get invocationTimeStamp
   * @return invocationTimeStamp
   **/
  @JsonProperty(value = "invocationTimeStamp")
  @ApiModelProperty(value = "")
  
  public Date getInvocationTimeStamp() {
    return invocationTimeStamp;
  }

  public void setInvocationTimeStamp(Date invocationTimeStamp) {
    this.invocationTimeStamp = invocationTimeStamp;
  }

  public ChargingDataResponse invocationSequenceNumber(Integer invocationSequenceNumber) {
    this.invocationSequenceNumber = invocationSequenceNumber;
    return this;
  }

  /**
   * Get invocationSequenceNumber
   * minimum: 0
   * @return invocationSequenceNumber
   **/
  @JsonProperty(value = "invocationSequenceNumber")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(0)
  public Integer getInvocationSequenceNumber() {
    return invocationSequenceNumber;
  }

  public void setInvocationSequenceNumber(Integer invocationSequenceNumber) {
    this.invocationSequenceNumber = invocationSequenceNumber;
  }

  public ChargingDataResponse invocationResult(InvocationResult invocationResult) {
    this.invocationResult = invocationResult;
    return this;
  }

  /**
   * Get invocationResult
   * @return invocationResult
   **/
  @JsonProperty(value = "invocationResult")
  @ApiModelProperty(value = "")
  @Valid 
  public InvocationResult getInvocationResult() {
    return invocationResult;
  }

  public void setInvocationResult(InvocationResult invocationResult) {
    this.invocationResult = invocationResult;
  }

  public ChargingDataResponse sessionFailover(SessionFailover sessionFailover) {
    this.sessionFailover = sessionFailover;
    return this;
  }

  /**
   * Get sessionFailover
   * @return sessionFailover
   **/
  @JsonProperty(value = "sessionFailover")
  @ApiModelProperty(value = "")
  
  public SessionFailover getSessionFailover() {
    return sessionFailover;
  }

  public void setSessionFailover(SessionFailover sessionFailover) {
    this.sessionFailover = sessionFailover;
  }

  public ChargingDataResponse multipleUnitInformation(List<@Valid MultipleUnitInformation> multipleUnitInformation) {
    this.multipleUnitInformation = multipleUnitInformation;
    return this;
  }

  public ChargingDataResponse addMultipleUnitInformationItem(MultipleUnitInformation multipleUnitInformationItem) {
    if (this.multipleUnitInformation == null) {
      this.multipleUnitInformation = new ArrayList<>();
    }
    this.multipleUnitInformation.add(multipleUnitInformationItem);
    return this;
  }

  /**
   * Get multipleUnitInformation
   * @return multipleUnitInformation
   **/
  @JsonProperty(value = "multipleUnitInformation")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid MultipleUnitInformation> getMultipleUnitInformation() {
    return multipleUnitInformation;
  }

  public void setMultipleUnitInformation(List<@Valid MultipleUnitInformation> multipleUnitInformation) {
    this.multipleUnitInformation = multipleUnitInformation;
  }

  public ChargingDataResponse triggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public ChargingDataResponse addTriggersItem(Trigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

  /**
   * Get triggers
   * @return triggers
   **/
  @JsonProperty(value = "triggers")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Trigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
  }

  public ChargingDataResponse pDUSessionChargingInformation(PDUSessionChargingInformation pDUSessionChargingInformation) {
    this.pDUSessionChargingInformation = pDUSessionChargingInformation;
    return this;
  }

  /**
   * Get pDUSessionChargingInformation
   * @return pDUSessionChargingInformation
   **/
  @JsonProperty(value = "pDUSessionChargingInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public PDUSessionChargingInformation getpDUSessionChargingInformation() {
    return pDUSessionChargingInformation;
  }

  public void setpDUSessionChargingInformation(PDUSessionChargingInformation pDUSessionChargingInformation) {
    this.pDUSessionChargingInformation = pDUSessionChargingInformation;
  }

  public ChargingDataResponse roamingQBCInformation(RoamingQBCInformation roamingQBCInformation) {
    this.roamingQBCInformation = roamingQBCInformation;
    return this;
  }

  /**
   * Get roamingQBCInformation
   * @return roamingQBCInformation
   **/
  @JsonProperty(value = "roamingQBCInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public RoamingQBCInformation getRoamingQBCInformation() {
    return roamingQBCInformation;
  }

  public void setRoamingQBCInformation(RoamingQBCInformation roamingQBCInformation) {
    this.roamingQBCInformation = roamingQBCInformation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingDataResponse chargingDataResponse = (ChargingDataResponse) o;
    return Objects.equals(this.invocationTimeStamp, chargingDataResponse.invocationTimeStamp) &&
        Objects.equals(this.invocationSequenceNumber, chargingDataResponse.invocationSequenceNumber) &&
        Objects.equals(this.invocationResult, chargingDataResponse.invocationResult) &&
        Objects.equals(this.sessionFailover, chargingDataResponse.sessionFailover) &&
        Objects.equals(this.multipleUnitInformation, chargingDataResponse.multipleUnitInformation) &&
        Objects.equals(this.triggers, chargingDataResponse.triggers) &&
        Objects.equals(this.pDUSessionChargingInformation, chargingDataResponse.pDUSessionChargingInformation) &&
        Objects.equals(this.roamingQBCInformation, chargingDataResponse.roamingQBCInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invocationTimeStamp, invocationSequenceNumber, invocationResult, sessionFailover, multipleUnitInformation, triggers, pDUSessionChargingInformation, roamingQBCInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingDataResponse {\n");
    
    sb.append("    invocationTimeStamp: ").append(toIndentedString(invocationTimeStamp)).append("\n");
    sb.append("    invocationSequenceNumber: ").append(toIndentedString(invocationSequenceNumber)).append("\n");
    sb.append("    invocationResult: ").append(toIndentedString(invocationResult)).append("\n");
    sb.append("    sessionFailover: ").append(toIndentedString(sessionFailover)).append("\n");
    sb.append("    multipleUnitInformation: ").append(toIndentedString(multipleUnitInformation)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    pDUSessionChargingInformation: ").append(toIndentedString(pDUSessionChargingInformation)).append("\n");
    sb.append("    roamingQBCInformation: ").append(toIndentedString(roamingQBCInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

