/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GlobalRanNodeId
 */
@JsonPropertyOrder({
  GlobalRanNodeId.JSON_PROPERTY_PLMN_ID,
  GlobalRanNodeId.JSON_PROPERTY_N3_IWF_ID,
  GlobalRanNodeId.JSON_PROPERTY_G_NB_ID,
  GlobalRanNodeId.JSON_PROPERTY_NGE_NB_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class GlobalRanNodeId   {
  public static final String JSON_PROPERTY_PLMN_ID = "plmnId";
  @JsonProperty(JSON_PROPERTY_PLMN_ID)
  private PlmnId plmnId;

  public static final String JSON_PROPERTY_N3_IWF_ID = "n3IwfId";
  @JsonProperty(JSON_PROPERTY_N3_IWF_ID)
  private String n3IwfId;

  public static final String JSON_PROPERTY_G_NB_ID = "gNbId";
  @JsonProperty(JSON_PROPERTY_G_NB_ID)
  private GNbId gNbId;

  public static final String JSON_PROPERTY_NGE_NB_ID = "ngeNbId";
  @JsonProperty(JSON_PROPERTY_NGE_NB_ID)
  private String ngeNbId;

  public GlobalRanNodeId plmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
    return this;
  }

  /**
   * Get plmnId
   * @return plmnId
   **/
  @JsonProperty(value = "plmnId")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public PlmnId getPlmnId() {
    return plmnId;
  }

  public void setPlmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
  }

  public GlobalRanNodeId n3IwfId(String n3IwfId) {
    this.n3IwfId = n3IwfId;
    return this;
  }

  /**
   * Get n3IwfId
   * @return n3IwfId
   **/
  @JsonProperty(value = "n3IwfId")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^[A-Fa-f0-9]+$")
  public String getN3IwfId() {
    return n3IwfId;
  }

  public void setN3IwfId(String n3IwfId) {
    this.n3IwfId = n3IwfId;
  }

  public GlobalRanNodeId gNbId(GNbId gNbId) {
    this.gNbId = gNbId;
    return this;
  }

  /**
   * Get gNbId
   * @return gNbId
   **/
  @JsonProperty(value = "gNbId")
  @ApiModelProperty(value = "")
  @Valid 
  public GNbId getgNbId() {
    return gNbId;
  }

  public void setgNbId(GNbId gNbId) {
    this.gNbId = gNbId;
  }

  public GlobalRanNodeId ngeNbId(String ngeNbId) {
    this.ngeNbId = ngeNbId;
    return this;
  }

  /**
   * Get ngeNbId
   * @return ngeNbId
   **/
  @JsonProperty(value = "ngeNbId")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^(MacroNGeNB-[A-Fa-f0-9]{5}|LMacroNGeNB-[A-Fa-f0-9]{6}|SMacroNGeNB-[A-Fa-f0-9]{5})$")
  public String getNgeNbId() {
    return ngeNbId;
  }

  public void setNgeNbId(String ngeNbId) {
    this.ngeNbId = ngeNbId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalRanNodeId globalRanNodeId = (GlobalRanNodeId) o;
    return Objects.equals(this.plmnId, globalRanNodeId.plmnId) &&
        Objects.equals(this.n3IwfId, globalRanNodeId.n3IwfId) &&
        Objects.equals(this.gNbId, globalRanNodeId.gNbId) &&
        Objects.equals(this.ngeNbId, globalRanNodeId.ngeNbId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plmnId, n3IwfId, gNbId, ngeNbId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalRanNodeId {\n");
    
    sb.append("    plmnId: ").append(toIndentedString(plmnId)).append("\n");
    sb.append("    n3IwfId: ").append(toIndentedString(n3IwfId)).append("\n");
    sb.append("    gNbId: ").append(toIndentedString(gNbId)).append("\n");
    sb.append("    ngeNbId: ").append(toIndentedString(ngeNbId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

