/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * InvocationResult
 */
@JsonPropertyOrder({
  InvocationResult.JSON_PROPERTY_ERROR,
  InvocationResult.JSON_PROPERTY_FAILURE_HANDLING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class InvocationResult   {
  public static final String JSON_PROPERTY_ERROR = "error";
  @JsonProperty(JSON_PROPERTY_ERROR)
  private ProblemDetails error;

  public static final String JSON_PROPERTY_FAILURE_HANDLING = "failureHandling";
  @JsonProperty(JSON_PROPERTY_FAILURE_HANDLING)
  private FailureHandling failureHandling;

  public InvocationResult error(ProblemDetails error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   **/
  @JsonProperty(value = "error")
  @ApiModelProperty(value = "")
  @Valid 
  public ProblemDetails getError() {
    return error;
  }

  public void setError(ProblemDetails error) {
    this.error = error;
  }

  public InvocationResult failureHandling(FailureHandling failureHandling) {
    this.failureHandling = failureHandling;
    return this;
  }

  /**
   * Get failureHandling
   * @return failureHandling
   **/
  @JsonProperty(value = "failureHandling")
  @ApiModelProperty(value = "")
  
  public FailureHandling getFailureHandling() {
    return failureHandling;
  }

  public void setFailureHandling(FailureHandling failureHandling) {
    this.failureHandling = failureHandling;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvocationResult invocationResult = (InvocationResult) o;
    return Objects.equals(this.error, invocationResult.error) &&
        Objects.equals(this.failureHandling, invocationResult.failureHandling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, failureHandling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvocationResult {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    failureHandling: ").append(toIndentedString(failureHandling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

