/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * MultipleUnitInformation
 */
@JsonPropertyOrder({
  MultipleUnitInformation.JSON_PROPERTY_RESULT_CODE,
  MultipleUnitInformation.JSON_PROPERTY_RATING_GROUP,
  MultipleUnitInformation.JSON_PROPERTY_GRANTED_UNIT,
  MultipleUnitInformation.JSON_PROPERTY_TRIGGERS,
  MultipleUnitInformation.JSON_PROPERTY_VALIDITY_TIME,
  MultipleUnitInformation.JSON_PROPERTY_QUOTA_HOLDING_TIME,
  MultipleUnitInformation.JSON_PROPERTY_FINAL_UNIT_INDICATION,
  MultipleUnitInformation.JSON_PROPERTY_TIME_QUOTA_THRESHOLD,
  MultipleUnitInformation.JSON_PROPERTY_VOLUME_QUOTA_THRESHOLD,
  MultipleUnitInformation.JSON_PROPERTY_UNIT_QUOTA_THRESHOLD,
  MultipleUnitInformation.JSON_PROPERTY_U_P_F_I_D
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class MultipleUnitInformation   {
  public static final String JSON_PROPERTY_RESULT_CODE = "resultCode";
  @JsonProperty(JSON_PROPERTY_RESULT_CODE)
  private ResultCode resultCode;

  public static final String JSON_PROPERTY_RATING_GROUP = "ratingGroup";
  @JsonProperty(JSON_PROPERTY_RATING_GROUP)
  private Integer ratingGroup;

  public static final String JSON_PROPERTY_GRANTED_UNIT = "grantedUnit";
  @JsonProperty(JSON_PROPERTY_GRANTED_UNIT)
  private GrantedUnit grantedUnit;

  public static final String JSON_PROPERTY_TRIGGERS = "triggers";
  @JsonProperty(JSON_PROPERTY_TRIGGERS)
  private List<@Valid Trigger> triggers;

  public static final String JSON_PROPERTY_VALIDITY_TIME = "validityTime";
  @JsonProperty(JSON_PROPERTY_VALIDITY_TIME)
  private Integer validityTime;

  public static final String JSON_PROPERTY_QUOTA_HOLDING_TIME = "quotaHoldingTime";
  @JsonProperty(JSON_PROPERTY_QUOTA_HOLDING_TIME)
  private Integer quotaHoldingTime;

  public static final String JSON_PROPERTY_FINAL_UNIT_INDICATION = "finalUnitIndication";
  @JsonProperty(JSON_PROPERTY_FINAL_UNIT_INDICATION)
  private FinalUnitIndication finalUnitIndication;

  public static final String JSON_PROPERTY_TIME_QUOTA_THRESHOLD = "timeQuotaThreshold";
  @JsonProperty(JSON_PROPERTY_TIME_QUOTA_THRESHOLD)
  private Integer timeQuotaThreshold;

  public static final String JSON_PROPERTY_VOLUME_QUOTA_THRESHOLD = "volumeQuotaThreshold";
  @JsonProperty(JSON_PROPERTY_VOLUME_QUOTA_THRESHOLD)
  private Long volumeQuotaThreshold;

  public static final String JSON_PROPERTY_UNIT_QUOTA_THRESHOLD = "unitQuotaThreshold";
  @JsonProperty(JSON_PROPERTY_UNIT_QUOTA_THRESHOLD)
  private Integer unitQuotaThreshold;

  public static final String JSON_PROPERTY_U_P_F_I_D = "uPFID";
  @JsonProperty(JSON_PROPERTY_U_P_F_I_D)
  private UUID uPFID;

  public MultipleUnitInformation resultCode(ResultCode resultCode) {
    this.resultCode = resultCode;
    return this;
  }

  /**
   * Get resultCode
   * @return resultCode
   **/
  @JsonProperty(value = "resultCode")
  @ApiModelProperty(value = "")
  
  public ResultCode getResultCode() {
    return resultCode;
  }

  public void setResultCode(ResultCode resultCode) {
    this.resultCode = resultCode;
  }

  public MultipleUnitInformation ratingGroup(Integer ratingGroup) {
    this.ratingGroup = ratingGroup;
    return this;
  }

  /**
   * Get ratingGroup
   * minimum: 0
   * @return ratingGroup
   **/
  @JsonProperty(value = "ratingGroup")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(0)
  public Integer getRatingGroup() {
    return ratingGroup;
  }

  public void setRatingGroup(Integer ratingGroup) {
    this.ratingGroup = ratingGroup;
  }

  public MultipleUnitInformation grantedUnit(GrantedUnit grantedUnit) {
    this.grantedUnit = grantedUnit;
    return this;
  }

  /**
   * Get grantedUnit
   * @return grantedUnit
   **/
  @JsonProperty(value = "grantedUnit")
  @ApiModelProperty(value = "")
  @Valid 
  public GrantedUnit getGrantedUnit() {
    return grantedUnit;
  }

  public void setGrantedUnit(GrantedUnit grantedUnit) {
    this.grantedUnit = grantedUnit;
  }

  public MultipleUnitInformation triggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public MultipleUnitInformation addTriggersItem(Trigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

  /**
   * Get triggers
   * @return triggers
   **/
  @JsonProperty(value = "triggers")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Trigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
  }

  public MultipleUnitInformation validityTime(Integer validityTime) {
    this.validityTime = validityTime;
    return this;
  }

  /**
   * Get validityTime
   * @return validityTime
   **/
  @JsonProperty(value = "validityTime")
  @ApiModelProperty(value = "")
  
  public Integer getValidityTime() {
    return validityTime;
  }

  public void setValidityTime(Integer validityTime) {
    this.validityTime = validityTime;
  }

  public MultipleUnitInformation quotaHoldingTime(Integer quotaHoldingTime) {
    this.quotaHoldingTime = quotaHoldingTime;
    return this;
  }

  /**
   * Get quotaHoldingTime
   * @return quotaHoldingTime
   **/
  @JsonProperty(value = "quotaHoldingTime")
  @ApiModelProperty(value = "")
  
  public Integer getQuotaHoldingTime() {
    return quotaHoldingTime;
  }

  public void setQuotaHoldingTime(Integer quotaHoldingTime) {
    this.quotaHoldingTime = quotaHoldingTime;
  }

  public MultipleUnitInformation finalUnitIndication(FinalUnitIndication finalUnitIndication) {
    this.finalUnitIndication = finalUnitIndication;
    return this;
  }

  /**
   * Get finalUnitIndication
   * @return finalUnitIndication
   **/
  @JsonProperty(value = "finalUnitIndication")
  @ApiModelProperty(value = "")
  @Valid 
  public FinalUnitIndication getFinalUnitIndication() {
    return finalUnitIndication;
  }

  public void setFinalUnitIndication(FinalUnitIndication finalUnitIndication) {
    this.finalUnitIndication = finalUnitIndication;
  }

  public MultipleUnitInformation timeQuotaThreshold(Integer timeQuotaThreshold) {
    this.timeQuotaThreshold = timeQuotaThreshold;
    return this;
  }

  /**
   * Get timeQuotaThreshold
   * @return timeQuotaThreshold
   **/
  @JsonProperty(value = "timeQuotaThreshold")
  @ApiModelProperty(value = "")
  
  public Integer getTimeQuotaThreshold() {
    return timeQuotaThreshold;
  }

  public void setTimeQuotaThreshold(Integer timeQuotaThreshold) {
    this.timeQuotaThreshold = timeQuotaThreshold;
  }

  public MultipleUnitInformation volumeQuotaThreshold(Long volumeQuotaThreshold) {
    this.volumeQuotaThreshold = volumeQuotaThreshold;
    return this;
  }

  /**
   * Get volumeQuotaThreshold
   * minimum: 0
   * @return volumeQuotaThreshold
   **/
  @JsonProperty(value = "volumeQuotaThreshold")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getVolumeQuotaThreshold() {
    return volumeQuotaThreshold;
  }

  public void setVolumeQuotaThreshold(Long volumeQuotaThreshold) {
    this.volumeQuotaThreshold = volumeQuotaThreshold;
  }

  public MultipleUnitInformation unitQuotaThreshold(Integer unitQuotaThreshold) {
    this.unitQuotaThreshold = unitQuotaThreshold;
    return this;
  }

  /**
   * Get unitQuotaThreshold
   * @return unitQuotaThreshold
   **/
  @JsonProperty(value = "unitQuotaThreshold")
  @ApiModelProperty(value = "")
  
  public Integer getUnitQuotaThreshold() {
    return unitQuotaThreshold;
  }

  public void setUnitQuotaThreshold(Integer unitQuotaThreshold) {
    this.unitQuotaThreshold = unitQuotaThreshold;
  }

  public MultipleUnitInformation uPFID(UUID uPFID) {
    this.uPFID = uPFID;
    return this;
  }

  /**
   * Get uPFID
   * @return uPFID
   **/
  @JsonProperty(value = "uPFID")
  @ApiModelProperty(value = "")
  
  public UUID getuPFID() {
    return uPFID;
  }

  public void setuPFID(UUID uPFID) {
    this.uPFID = uPFID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultipleUnitInformation multipleUnitInformation = (MultipleUnitInformation) o;
    return Objects.equals(this.resultCode, multipleUnitInformation.resultCode) &&
        Objects.equals(this.ratingGroup, multipleUnitInformation.ratingGroup) &&
        Objects.equals(this.grantedUnit, multipleUnitInformation.grantedUnit) &&
        Objects.equals(this.triggers, multipleUnitInformation.triggers) &&
        Objects.equals(this.validityTime, multipleUnitInformation.validityTime) &&
        Objects.equals(this.quotaHoldingTime, multipleUnitInformation.quotaHoldingTime) &&
        Objects.equals(this.finalUnitIndication, multipleUnitInformation.finalUnitIndication) &&
        Objects.equals(this.timeQuotaThreshold, multipleUnitInformation.timeQuotaThreshold) &&
        Objects.equals(this.volumeQuotaThreshold, multipleUnitInformation.volumeQuotaThreshold) &&
        Objects.equals(this.unitQuotaThreshold, multipleUnitInformation.unitQuotaThreshold) &&
        Objects.equals(this.uPFID, multipleUnitInformation.uPFID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultCode, ratingGroup, grantedUnit, triggers, validityTime, quotaHoldingTime, finalUnitIndication, timeQuotaThreshold, volumeQuotaThreshold, unitQuotaThreshold, uPFID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultipleUnitInformation {\n");
    
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("    ratingGroup: ").append(toIndentedString(ratingGroup)).append("\n");
    sb.append("    grantedUnit: ").append(toIndentedString(grantedUnit)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    validityTime: ").append(toIndentedString(validityTime)).append("\n");
    sb.append("    quotaHoldingTime: ").append(toIndentedString(quotaHoldingTime)).append("\n");
    sb.append("    finalUnitIndication: ").append(toIndentedString(finalUnitIndication)).append("\n");
    sb.append("    timeQuotaThreshold: ").append(toIndentedString(timeQuotaThreshold)).append("\n");
    sb.append("    volumeQuotaThreshold: ").append(toIndentedString(volumeQuotaThreshold)).append("\n");
    sb.append("    unitQuotaThreshold: ").append(toIndentedString(unitQuotaThreshold)).append("\n");
    sb.append("    uPFID: ").append(toIndentedString(uPFID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

