/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * MultipleQFIcontainer
 */
@JsonPropertyOrder({
  MultipleQFIcontainer.JSON_PROPERTY_TRIGGERS,
  MultipleQFIcontainer.JSON_PROPERTY_TRIGGER_TIMESTAMP,
  MultipleQFIcontainer.JSON_PROPERTY_TIME,
  MultipleQFIcontainer.JSON_PROPERTY_TOTAL_VOLUME,
  MultipleQFIcontainer.JSON_PROPERTY_UPLINK_VOLUME,
  MultipleQFIcontainer.JSON_PROPERTY_LOCAL_SEQUENCE_NUMBER,
  MultipleQFIcontainer.JSON_PROPERTY_Q_F_I_CONTAINER_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class MultipleQFIcontainer   {
  public static final String JSON_PROPERTY_TRIGGERS = "triggers";
  @JsonProperty(JSON_PROPERTY_TRIGGERS)
  private List<@Valid Trigger> triggers;

  public static final String JSON_PROPERTY_TRIGGER_TIMESTAMP = "triggerTimestamp";
  @JsonProperty(JSON_PROPERTY_TRIGGER_TIMESTAMP)
  private Date triggerTimestamp;

  public static final String JSON_PROPERTY_TIME = "time";
  @JsonProperty(JSON_PROPERTY_TIME)
  private Integer time;

  public static final String JSON_PROPERTY_TOTAL_VOLUME = "totalVolume";
  @JsonProperty(JSON_PROPERTY_TOTAL_VOLUME)
  private Long totalVolume;

  public static final String JSON_PROPERTY_UPLINK_VOLUME = "uplinkVolume";
  @JsonProperty(JSON_PROPERTY_UPLINK_VOLUME)
  private Long uplinkVolume;

  public static final String JSON_PROPERTY_LOCAL_SEQUENCE_NUMBER = "localSequenceNumber";
  @JsonProperty(JSON_PROPERTY_LOCAL_SEQUENCE_NUMBER)
  private Integer localSequenceNumber;

  public static final String JSON_PROPERTY_Q_F_I_CONTAINER_INFORMATION = "qFIContainerInformation";
  @JsonProperty(JSON_PROPERTY_Q_F_I_CONTAINER_INFORMATION)
  private QFIContainerInformation qFIContainerInformation;

  public MultipleQFIcontainer triggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public MultipleQFIcontainer addTriggersItem(Trigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

  /**
   * Get triggers
   * @return triggers
   **/
  @JsonProperty(value = "triggers")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Trigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
  }

  public MultipleQFIcontainer triggerTimestamp(Date triggerTimestamp) {
    this.triggerTimestamp = triggerTimestamp;
    return this;
  }

  /**
   * Get triggerTimestamp
   * @return triggerTimestamp
   **/
  @JsonProperty(value = "triggerTimestamp")
  @ApiModelProperty(value = "")
  
  public Date getTriggerTimestamp() {
    return triggerTimestamp;
  }

  public void setTriggerTimestamp(Date triggerTimestamp) {
    this.triggerTimestamp = triggerTimestamp;
  }

  public MultipleQFIcontainer time(Integer time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   * minimum: 0
   * @return time
   **/
  @JsonProperty(value = "time")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public MultipleQFIcontainer totalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
    return this;
  }

  /**
   * Get totalVolume
   * minimum: 0
   * @return totalVolume
   **/
  @JsonProperty(value = "totalVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getTotalVolume() {
    return totalVolume;
  }

  public void setTotalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
  }

  public MultipleQFIcontainer uplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
    return this;
  }

  /**
   * Get uplinkVolume
   * minimum: 0
   * @return uplinkVolume
   **/
  @JsonProperty(value = "uplinkVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getUplinkVolume() {
    return uplinkVolume;
  }

  public void setUplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
  }

  public MultipleQFIcontainer localSequenceNumber(Integer localSequenceNumber) {
    this.localSequenceNumber = localSequenceNumber;
    return this;
  }

  /**
   * Get localSequenceNumber
   * @return localSequenceNumber
   **/
  @JsonProperty(value = "localSequenceNumber")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getLocalSequenceNumber() {
    return localSequenceNumber;
  }

  public void setLocalSequenceNumber(Integer localSequenceNumber) {
    this.localSequenceNumber = localSequenceNumber;
  }

  public MultipleQFIcontainer qFIContainerInformation(QFIContainerInformation qFIContainerInformation) {
    this.qFIContainerInformation = qFIContainerInformation;
    return this;
  }

  /**
   * Get qFIContainerInformation
   * @return qFIContainerInformation
   **/
  @JsonProperty(value = "qFIContainerInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public QFIContainerInformation getqFIContainerInformation() {
    return qFIContainerInformation;
  }

  public void setqFIContainerInformation(QFIContainerInformation qFIContainerInformation) {
    this.qFIContainerInformation = qFIContainerInformation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultipleQFIcontainer multipleQFIcontainer = (MultipleQFIcontainer) o;
    return Objects.equals(this.triggers, multipleQFIcontainer.triggers) &&
        Objects.equals(this.triggerTimestamp, multipleQFIcontainer.triggerTimestamp) &&
        Objects.equals(this.time, multipleQFIcontainer.time) &&
        Objects.equals(this.totalVolume, multipleQFIcontainer.totalVolume) &&
        Objects.equals(this.uplinkVolume, multipleQFIcontainer.uplinkVolume) &&
        Objects.equals(this.localSequenceNumber, multipleQFIcontainer.localSequenceNumber) &&
        Objects.equals(this.qFIContainerInformation, multipleQFIcontainer.qFIContainerInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(triggers, triggerTimestamp, time, totalVolume, uplinkVolume, localSequenceNumber, qFIContainerInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultipleQFIcontainer {\n");
    
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    triggerTimestamp: ").append(toIndentedString(triggerTimestamp)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    totalVolume: ").append(toIndentedString(totalVolume)).append("\n");
    sb.append("    uplinkVolume: ").append(toIndentedString(uplinkVolume)).append("\n");
    sb.append("    localSequenceNumber: ").append(toIndentedString(localSequenceNumber)).append("\n");
    sb.append("    qFIContainerInformation: ").append(toIndentedString(qFIContainerInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

