/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * NetworkSlicingInfo
 */
@JsonPropertyOrder({
  NetworkSlicingInfo.JSON_PROPERTY_S_N_S_S_A_I
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class NetworkSlicingInfo   {
  public static final String JSON_PROPERTY_S_N_S_S_A_I = "sNSSAI";
  @JsonProperty(JSON_PROPERTY_S_N_S_S_A_I)
  private Snssai sNSSAI;

  public NetworkSlicingInfo sNSSAI(Snssai sNSSAI) {
    this.sNSSAI = sNSSAI;
    return this;
  }

  /**
   * Get sNSSAI
   * @return sNSSAI
   **/
  @JsonProperty(value = "sNSSAI")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public Snssai getsNSSAI() {
    return sNSSAI;
  }

  public void setsNSSAI(Snssai sNSSAI) {
    this.sNSSAI = sNSSAI;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkSlicingInfo networkSlicingInfo = (NetworkSlicingInfo) o;
    return Objects.equals(this.sNSSAI, networkSlicingInfo.sNSSAI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sNSSAI);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkSlicingInfo {\n");
    
    sb.append("    sNSSAI: ").append(toIndentedString(sNSSAI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

