/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * PDUAddress
 */
@JsonPropertyOrder({
  PDUAddress.JSON_PROPERTY_PDU_I_PV4_ADDRESS,
  PDUAddress.JSON_PROPERTY_PDU_I_PV6_ADDRESSWITH_PREFIX,
  PDUAddress.JSON_PROPERTY_PDU_ADDRESSPREFIXLENGTH,
  PDUAddress.JSON_PROPERTY_I_PV4DYNAMIC_ADDRESS_FLAG,
  PDUAddress.JSON_PROPERTY_I_PV6DYNAMIC_PREFIX_FLAG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class PDUAddress   {
  public static final String JSON_PROPERTY_PDU_I_PV4_ADDRESS = "pduIPv4Address";
  @JsonProperty(JSON_PROPERTY_PDU_I_PV4_ADDRESS)
  private String pduIPv4Address;

  public static final String JSON_PROPERTY_PDU_I_PV6_ADDRESSWITH_PREFIX = "pduIPv6AddresswithPrefix";
  @JsonProperty(JSON_PROPERTY_PDU_I_PV6_ADDRESSWITH_PREFIX)
  private Ipv6Addr pduIPv6AddresswithPrefix;

  public static final String JSON_PROPERTY_PDU_ADDRESSPREFIXLENGTH = "pduAddressprefixlength";
  @JsonProperty(JSON_PROPERTY_PDU_ADDRESSPREFIXLENGTH)
  private Integer pduAddressprefixlength;

  public static final String JSON_PROPERTY_I_PV4DYNAMIC_ADDRESS_FLAG = "iPv4dynamicAddressFlag";
  @JsonProperty(JSON_PROPERTY_I_PV4DYNAMIC_ADDRESS_FLAG)
  private Boolean iPv4dynamicAddressFlag;

  public static final String JSON_PROPERTY_I_PV6DYNAMIC_PREFIX_FLAG = "iPv6dynamicPrefixFlag";
  @JsonProperty(JSON_PROPERTY_I_PV6DYNAMIC_PREFIX_FLAG)
  private Boolean iPv6dynamicPrefixFlag;

  public PDUAddress pduIPv4Address(String pduIPv4Address) {
    this.pduIPv4Address = pduIPv4Address;
    return this;
  }

  /**
   * Get pduIPv4Address
   * @return pduIPv4Address
   **/
  @JsonProperty(value = "pduIPv4Address")
  @ApiModelProperty(example = "198.51.100.1", value = "")
   @Pattern(regexp="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$")
  public String getPduIPv4Address() {
    return pduIPv4Address;
  }

  public void setPduIPv4Address(String pduIPv4Address) {
    this.pduIPv4Address = pduIPv4Address;
  }

  public PDUAddress pduIPv6AddresswithPrefix(Ipv6Addr pduIPv6AddresswithPrefix) {
    this.pduIPv6AddresswithPrefix = pduIPv6AddresswithPrefix;
    return this;
  }

  /**
   * Get pduIPv6AddresswithPrefix
   * @return pduIPv6AddresswithPrefix
   **/
  @JsonProperty(value = "pduIPv6AddresswithPrefix")
  @ApiModelProperty(value = "")
  @Valid 
  public Ipv6Addr getPduIPv6AddresswithPrefix() {
    return pduIPv6AddresswithPrefix;
  }

  public void setPduIPv6AddresswithPrefix(Ipv6Addr pduIPv6AddresswithPrefix) {
    this.pduIPv6AddresswithPrefix = pduIPv6AddresswithPrefix;
  }

  public PDUAddress pduAddressprefixlength(Integer pduAddressprefixlength) {
    this.pduAddressprefixlength = pduAddressprefixlength;
    return this;
  }

  /**
   * Get pduAddressprefixlength
   * @return pduAddressprefixlength
   **/
  @JsonProperty(value = "pduAddressprefixlength")
  @ApiModelProperty(value = "")
  
  public Integer getPduAddressprefixlength() {
    return pduAddressprefixlength;
  }

  public void setPduAddressprefixlength(Integer pduAddressprefixlength) {
    this.pduAddressprefixlength = pduAddressprefixlength;
  }

  public PDUAddress iPv4dynamicAddressFlag(Boolean iPv4dynamicAddressFlag) {
    this.iPv4dynamicAddressFlag = iPv4dynamicAddressFlag;
    return this;
  }

  /**
   * Get iPv4dynamicAddressFlag
   * @return iPv4dynamicAddressFlag
   **/
  @JsonProperty(value = "iPv4dynamicAddressFlag")
  @ApiModelProperty(value = "")
  
  public Boolean getiPv4dynamicAddressFlag() {
    return iPv4dynamicAddressFlag;
  }

  public void setiPv4dynamicAddressFlag(Boolean iPv4dynamicAddressFlag) {
    this.iPv4dynamicAddressFlag = iPv4dynamicAddressFlag;
  }

  public PDUAddress iPv6dynamicPrefixFlag(Boolean iPv6dynamicPrefixFlag) {
    this.iPv6dynamicPrefixFlag = iPv6dynamicPrefixFlag;
    return this;
  }

  /**
   * Get iPv6dynamicPrefixFlag
   * @return iPv6dynamicPrefixFlag
   **/
  @JsonProperty(value = "iPv6dynamicPrefixFlag")
  @ApiModelProperty(value = "")
  
  public Boolean getiPv6dynamicPrefixFlag() {
    return iPv6dynamicPrefixFlag;
  }

  public void setiPv6dynamicPrefixFlag(Boolean iPv6dynamicPrefixFlag) {
    this.iPv6dynamicPrefixFlag = iPv6dynamicPrefixFlag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDUAddress pdUAddress = (PDUAddress) o;
    return Objects.equals(this.pduIPv4Address, pdUAddress.pduIPv4Address) &&
        Objects.equals(this.pduIPv6AddresswithPrefix, pdUAddress.pduIPv6AddresswithPrefix) &&
        Objects.equals(this.pduAddressprefixlength, pdUAddress.pduAddressprefixlength) &&
        Objects.equals(this.iPv4dynamicAddressFlag, pdUAddress.iPv4dynamicAddressFlag) &&
        Objects.equals(this.iPv6dynamicPrefixFlag, pdUAddress.iPv6dynamicPrefixFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pduIPv4Address, pduIPv6AddresswithPrefix, pduAddressprefixlength, iPv4dynamicAddressFlag, iPv6dynamicPrefixFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDUAddress {\n");
    
    sb.append("    pduIPv4Address: ").append(toIndentedString(pduIPv4Address)).append("\n");
    sb.append("    pduIPv6AddresswithPrefix: ").append(toIndentedString(pduIPv6AddresswithPrefix)).append("\n");
    sb.append("    pduAddressprefixlength: ").append(toIndentedString(pduAddressprefixlength)).append("\n");
    sb.append("    iPv4dynamicAddressFlag: ").append(toIndentedString(iPv4dynamicAddressFlag)).append("\n");
    sb.append("    iPv6dynamicPrefixFlag: ").append(toIndentedString(iPv6dynamicPrefixFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

