/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * PresenceInfo
 */
@JsonPropertyOrder({
  PresenceInfo.JSON_PROPERTY_PRA_ID,
  PresenceInfo.JSON_PROPERTY_PRESENCE_STATE,
  PresenceInfo.JSON_PROPERTY_TRACKING_AREA_LIST,
  PresenceInfo.JSON_PROPERTY_ECGI_LIST,
  PresenceInfo.JSON_PROPERTY_NCGI_LIST,
  PresenceInfo.JSON_PROPERTY_GLOBAL_RAN_NODE_ID_LIST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class PresenceInfo   {
  public static final String JSON_PROPERTY_PRA_ID = "praId";
  @JsonProperty(JSON_PROPERTY_PRA_ID)
  private String praId;

  public static final String JSON_PROPERTY_PRESENCE_STATE = "presenceState";
  @JsonProperty(JSON_PROPERTY_PRESENCE_STATE)
  private PresenceState presenceState;

  public static final String JSON_PROPERTY_TRACKING_AREA_LIST = "trackingAreaList";
  @JsonProperty(JSON_PROPERTY_TRACKING_AREA_LIST)
  private List<@Valid Tai> trackingAreaList;

  public static final String JSON_PROPERTY_ECGI_LIST = "ecgiList";
  @JsonProperty(JSON_PROPERTY_ECGI_LIST)
  private List<@Valid Ecgi> ecgiList;

  public static final String JSON_PROPERTY_NCGI_LIST = "ncgiList";
  @JsonProperty(JSON_PROPERTY_NCGI_LIST)
  private List<@Valid Ncgi> ncgiList;

  public static final String JSON_PROPERTY_GLOBAL_RAN_NODE_ID_LIST = "globalRanNodeIdList";
  @JsonProperty(JSON_PROPERTY_GLOBAL_RAN_NODE_ID_LIST)
  private List<@Valid GlobalRanNodeId> globalRanNodeIdList;

  public PresenceInfo praId(String praId) {
    this.praId = praId;
    return this;
  }

  /**
   * Get praId
   * @return praId
   **/
  @JsonProperty(value = "praId")
  @ApiModelProperty(value = "")
  
  public String getPraId() {
    return praId;
  }

  public void setPraId(String praId) {
    this.praId = praId;
  }

  public PresenceInfo presenceState(PresenceState presenceState) {
    this.presenceState = presenceState;
    return this;
  }

  /**
   * Get presenceState
   * @return presenceState
   **/
  @JsonProperty(value = "presenceState")
  @ApiModelProperty(value = "")
  
  public PresenceState getPresenceState() {
    return presenceState;
  }

  public void setPresenceState(PresenceState presenceState) {
    this.presenceState = presenceState;
  }

  public PresenceInfo trackingAreaList(List<@Valid Tai> trackingAreaList) {
    this.trackingAreaList = trackingAreaList;
    return this;
  }

  public PresenceInfo addTrackingAreaListItem(Tai trackingAreaListItem) {
    if (this.trackingAreaList == null) {
      this.trackingAreaList = new ArrayList<>();
    }
    this.trackingAreaList.add(trackingAreaListItem);
    return this;
  }

  /**
   * Get trackingAreaList
   * @return trackingAreaList
   **/
  @JsonProperty(value = "trackingAreaList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=1)
  public List<@Valid Tai> getTrackingAreaList() {
    return trackingAreaList;
  }

  public void setTrackingAreaList(List<@Valid Tai> trackingAreaList) {
    this.trackingAreaList = trackingAreaList;
  }

  public PresenceInfo ecgiList(List<@Valid Ecgi> ecgiList) {
    this.ecgiList = ecgiList;
    return this;
  }

  public PresenceInfo addEcgiListItem(Ecgi ecgiListItem) {
    if (this.ecgiList == null) {
      this.ecgiList = new ArrayList<>();
    }
    this.ecgiList.add(ecgiListItem);
    return this;
  }

  /**
   * Get ecgiList
   * @return ecgiList
   **/
  @JsonProperty(value = "ecgiList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=1)
  public List<@Valid Ecgi> getEcgiList() {
    return ecgiList;
  }

  public void setEcgiList(List<@Valid Ecgi> ecgiList) {
    this.ecgiList = ecgiList;
  }

  public PresenceInfo ncgiList(List<@Valid Ncgi> ncgiList) {
    this.ncgiList = ncgiList;
    return this;
  }

  public PresenceInfo addNcgiListItem(Ncgi ncgiListItem) {
    if (this.ncgiList == null) {
      this.ncgiList = new ArrayList<>();
    }
    this.ncgiList.add(ncgiListItem);
    return this;
  }

  /**
   * Get ncgiList
   * @return ncgiList
   **/
  @JsonProperty(value = "ncgiList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=1)
  public List<@Valid Ncgi> getNcgiList() {
    return ncgiList;
  }

  public void setNcgiList(List<@Valid Ncgi> ncgiList) {
    this.ncgiList = ncgiList;
  }

  public PresenceInfo globalRanNodeIdList(List<@Valid GlobalRanNodeId> globalRanNodeIdList) {
    this.globalRanNodeIdList = globalRanNodeIdList;
    return this;
  }

  public PresenceInfo addGlobalRanNodeIdListItem(GlobalRanNodeId globalRanNodeIdListItem) {
    if (this.globalRanNodeIdList == null) {
      this.globalRanNodeIdList = new ArrayList<>();
    }
    this.globalRanNodeIdList.add(globalRanNodeIdListItem);
    return this;
  }

  /**
   * Get globalRanNodeIdList
   * @return globalRanNodeIdList
   **/
  @JsonProperty(value = "globalRanNodeIdList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=1)
  public List<@Valid GlobalRanNodeId> getGlobalRanNodeIdList() {
    return globalRanNodeIdList;
  }

  public void setGlobalRanNodeIdList(List<@Valid GlobalRanNodeId> globalRanNodeIdList) {
    this.globalRanNodeIdList = globalRanNodeIdList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresenceInfo presenceInfo = (PresenceInfo) o;
    return Objects.equals(this.praId, presenceInfo.praId) &&
        Objects.equals(this.presenceState, presenceInfo.presenceState) &&
        Objects.equals(this.trackingAreaList, presenceInfo.trackingAreaList) &&
        Objects.equals(this.ecgiList, presenceInfo.ecgiList) &&
        Objects.equals(this.ncgiList, presenceInfo.ncgiList) &&
        Objects.equals(this.globalRanNodeIdList, presenceInfo.globalRanNodeIdList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(praId, presenceState, trackingAreaList, ecgiList, ncgiList, globalRanNodeIdList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresenceInfo {\n");
    
    sb.append("    praId: ").append(toIndentedString(praId)).append("\n");
    sb.append("    presenceState: ").append(toIndentedString(presenceState)).append("\n");
    sb.append("    trackingAreaList: ").append(toIndentedString(trackingAreaList)).append("\n");
    sb.append("    ecgiList: ").append(toIndentedString(ecgiList)).append("\n");
    sb.append("    ncgiList: ").append(toIndentedString(ncgiList)).append("\n");
    sb.append("    globalRanNodeIdList: ").append(toIndentedString(globalRanNodeIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

