/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * QosFlowsUsageReport
 */
@JsonPropertyOrder({
  QosFlowsUsageReport.JSON_PROPERTY_Q_F_I,
  QosFlowsUsageReport.JSON_PROPERTY_START_TIMESTAMP,
  QosFlowsUsageReport.JSON_PROPERTY_END_TIMESTAMP,
  QosFlowsUsageReport.JSON_PROPERTY_UPLINK_VOLUME,
  QosFlowsUsageReport.JSON_PROPERTY_DOWNLINK_VOLUME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class QosFlowsUsageReport   {
  public static final String JSON_PROPERTY_Q_F_I = "qFI";
  @JsonProperty(JSON_PROPERTY_Q_F_I)
  private Integer qFI;

  public static final String JSON_PROPERTY_START_TIMESTAMP = "startTimestamp";
  @JsonProperty(JSON_PROPERTY_START_TIMESTAMP)
  private Date startTimestamp;

  public static final String JSON_PROPERTY_END_TIMESTAMP = "endTimestamp";
  @JsonProperty(JSON_PROPERTY_END_TIMESTAMP)
  private Date endTimestamp;

  public static final String JSON_PROPERTY_UPLINK_VOLUME = "uplinkVolume";
  @JsonProperty(JSON_PROPERTY_UPLINK_VOLUME)
  private Long uplinkVolume;

  public static final String JSON_PROPERTY_DOWNLINK_VOLUME = "downlinkVolume";
  @JsonProperty(JSON_PROPERTY_DOWNLINK_VOLUME)
  private Long downlinkVolume;

  public QosFlowsUsageReport qFI(Integer qFI) {
    this.qFI = qFI;
    return this;
  }

  /**
   * Get qFI
   * minimum: 0
   * maximum: 63
   * @return qFI
   **/
  @JsonProperty(value = "qFI")
  @ApiModelProperty(value = "")
   @Min(0) @Max(63)
  public Integer getqFI() {
    return qFI;
  }

  public void setqFI(Integer qFI) {
    this.qFI = qFI;
  }

  public QosFlowsUsageReport startTimestamp(Date startTimestamp) {
    this.startTimestamp = startTimestamp;
    return this;
  }

  /**
   * Get startTimestamp
   * @return startTimestamp
   **/
  @JsonProperty(value = "startTimestamp")
  @ApiModelProperty(value = "")
  
  public Date getStartTimestamp() {
    return startTimestamp;
  }

  public void setStartTimestamp(Date startTimestamp) {
    this.startTimestamp = startTimestamp;
  }

  public QosFlowsUsageReport endTimestamp(Date endTimestamp) {
    this.endTimestamp = endTimestamp;
    return this;
  }

  /**
   * Get endTimestamp
   * @return endTimestamp
   **/
  @JsonProperty(value = "endTimestamp")
  @ApiModelProperty(value = "")
  
  public Date getEndTimestamp() {
    return endTimestamp;
  }

  public void setEndTimestamp(Date endTimestamp) {
    this.endTimestamp = endTimestamp;
  }

  public QosFlowsUsageReport uplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
    return this;
  }

  /**
   * Get uplinkVolume
   * minimum: 0
   * @return uplinkVolume
   **/
  @JsonProperty(value = "uplinkVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getUplinkVolume() {
    return uplinkVolume;
  }

  public void setUplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
  }

  public QosFlowsUsageReport downlinkVolume(Long downlinkVolume) {
    this.downlinkVolume = downlinkVolume;
    return this;
  }

  /**
   * Get downlinkVolume
   * minimum: 0
   * @return downlinkVolume
   **/
  @JsonProperty(value = "downlinkVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getDownlinkVolume() {
    return downlinkVolume;
  }

  public void setDownlinkVolume(Long downlinkVolume) {
    this.downlinkVolume = downlinkVolume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QosFlowsUsageReport qosFlowsUsageReport = (QosFlowsUsageReport) o;
    return Objects.equals(this.qFI, qosFlowsUsageReport.qFI) &&
        Objects.equals(this.startTimestamp, qosFlowsUsageReport.startTimestamp) &&
        Objects.equals(this.endTimestamp, qosFlowsUsageReport.endTimestamp) &&
        Objects.equals(this.uplinkVolume, qosFlowsUsageReport.uplinkVolume) &&
        Objects.equals(this.downlinkVolume, qosFlowsUsageReport.downlinkVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qFI, startTimestamp, endTimestamp, uplinkVolume, downlinkVolume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QosFlowsUsageReport {\n");
    
    sb.append("    qFI: ").append(toIndentedString(qFI)).append("\n");
    sb.append("    startTimestamp: ").append(toIndentedString(startTimestamp)).append("\n");
    sb.append("    endTimestamp: ").append(toIndentedString(endTimestamp)).append("\n");
    sb.append("    uplinkVolume: ").append(toIndentedString(uplinkVolume)).append("\n");
    sb.append("    downlinkVolume: ").append(toIndentedString(downlinkVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

