/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RecipientInfo
 */
@JsonPropertyOrder({
  RecipientInfo.JSON_PROPERTY_RECIPIENT_S_U_P_I,
  RecipientInfo.JSON_PROPERTY_RECIPIENT_G_P_S_I,
  RecipientInfo.JSON_PROPERTY_RECIPIENT_OTHER_ADDRESS,
  RecipientInfo.JSON_PROPERTY_RECIPIENT_RECEIVED_ADDRESS,
  RecipientInfo.JSON_PROPERTY_RECIPIENT_S_C_C_P_ADDRESS,
  RecipientInfo.JSON_PROPERTY_S_M_DESTINATION_INTERFACE,
  RecipientInfo.JSON_PROPERTY_S_MRECIPIENT_PROTOCOL_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RecipientInfo   {
  public static final String JSON_PROPERTY_RECIPIENT_S_U_P_I = "recipientSUPI";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_S_U_P_I)
  private String recipientSUPI;

  public static final String JSON_PROPERTY_RECIPIENT_G_P_S_I = "recipientGPSI";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_G_P_S_I)
  private String recipientGPSI;

  public static final String JSON_PROPERTY_RECIPIENT_OTHER_ADDRESS = "recipientOtherAddress";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_OTHER_ADDRESS)
  private SMAddressInfo recipientOtherAddress;

  public static final String JSON_PROPERTY_RECIPIENT_RECEIVED_ADDRESS = "recipientReceivedAddress";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_RECEIVED_ADDRESS)
  private SMAddressInfo recipientReceivedAddress;

  public static final String JSON_PROPERTY_RECIPIENT_S_C_C_P_ADDRESS = "recipientSCCPAddress";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_S_C_C_P_ADDRESS)
  private String recipientSCCPAddress;

  public static final String JSON_PROPERTY_S_M_DESTINATION_INTERFACE = "sMDestinationInterface";
  @JsonProperty(JSON_PROPERTY_S_M_DESTINATION_INTERFACE)
  private SMInterface sMDestinationInterface;

  public static final String JSON_PROPERTY_S_MRECIPIENT_PROTOCOL_ID = "sMrecipientProtocolId";
  @JsonProperty(JSON_PROPERTY_S_MRECIPIENT_PROTOCOL_ID)
  private String sMrecipientProtocolId;

  public RecipientInfo recipientSUPI(String recipientSUPI) {
    this.recipientSUPI = recipientSUPI;
    return this;
  }

  /**
   * Get recipientSUPI
   * @return recipientSUPI
   **/
  @JsonProperty(value = "recipientSUPI")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^(imsi-[0-9]{5,15}|nai-.+|.+)$")
  public String getRecipientSUPI() {
    return recipientSUPI;
  }

  public void setRecipientSUPI(String recipientSUPI) {
    this.recipientSUPI = recipientSUPI;
  }

  public RecipientInfo recipientGPSI(String recipientGPSI) {
    this.recipientGPSI = recipientGPSI;
    return this;
  }

  /**
   * Get recipientGPSI
   * @return recipientGPSI
   **/
  @JsonProperty(value = "recipientGPSI")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$")
  public String getRecipientGPSI() {
    return recipientGPSI;
  }

  public void setRecipientGPSI(String recipientGPSI) {
    this.recipientGPSI = recipientGPSI;
  }

  public RecipientInfo recipientOtherAddress(SMAddressInfo recipientOtherAddress) {
    this.recipientOtherAddress = recipientOtherAddress;
    return this;
  }

  /**
   * Get recipientOtherAddress
   * @return recipientOtherAddress
   **/
  @JsonProperty(value = "recipientOtherAddress")
  @ApiModelProperty(value = "")
  @Valid 
  public SMAddressInfo getRecipientOtherAddress() {
    return recipientOtherAddress;
  }

  public void setRecipientOtherAddress(SMAddressInfo recipientOtherAddress) {
    this.recipientOtherAddress = recipientOtherAddress;
  }

  public RecipientInfo recipientReceivedAddress(SMAddressInfo recipientReceivedAddress) {
    this.recipientReceivedAddress = recipientReceivedAddress;
    return this;
  }

  /**
   * Get recipientReceivedAddress
   * @return recipientReceivedAddress
   **/
  @JsonProperty(value = "recipientReceivedAddress")
  @ApiModelProperty(value = "")
  @Valid 
  public SMAddressInfo getRecipientReceivedAddress() {
    return recipientReceivedAddress;
  }

  public void setRecipientReceivedAddress(SMAddressInfo recipientReceivedAddress) {
    this.recipientReceivedAddress = recipientReceivedAddress;
  }

  public RecipientInfo recipientSCCPAddress(String recipientSCCPAddress) {
    this.recipientSCCPAddress = recipientSCCPAddress;
    return this;
  }

  /**
   * Get recipientSCCPAddress
   * @return recipientSCCPAddress
   **/
  @JsonProperty(value = "recipientSCCPAddress")
  @ApiModelProperty(value = "")
  
  public String getRecipientSCCPAddress() {
    return recipientSCCPAddress;
  }

  public void setRecipientSCCPAddress(String recipientSCCPAddress) {
    this.recipientSCCPAddress = recipientSCCPAddress;
  }

  public RecipientInfo sMDestinationInterface(SMInterface sMDestinationInterface) {
    this.sMDestinationInterface = sMDestinationInterface;
    return this;
  }

  /**
   * Get sMDestinationInterface
   * @return sMDestinationInterface
   **/
  @JsonProperty(value = "sMDestinationInterface")
  @ApiModelProperty(value = "")
  @Valid 
  public SMInterface getsMDestinationInterface() {
    return sMDestinationInterface;
  }

  public void setsMDestinationInterface(SMInterface sMDestinationInterface) {
    this.sMDestinationInterface = sMDestinationInterface;
  }

  public RecipientInfo sMrecipientProtocolId(String sMrecipientProtocolId) {
    this.sMrecipientProtocolId = sMrecipientProtocolId;
    return this;
  }

  /**
   * Get sMrecipientProtocolId
   * @return sMrecipientProtocolId
   **/
  @JsonProperty(value = "sMrecipientProtocolId")
  @ApiModelProperty(value = "")
  
  public String getsMrecipientProtocolId() {
    return sMrecipientProtocolId;
  }

  public void setsMrecipientProtocolId(String sMrecipientProtocolId) {
    this.sMrecipientProtocolId = sMrecipientProtocolId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientInfo recipientInfo = (RecipientInfo) o;
    return Objects.equals(this.recipientSUPI, recipientInfo.recipientSUPI) &&
        Objects.equals(this.recipientGPSI, recipientInfo.recipientGPSI) &&
        Objects.equals(this.recipientOtherAddress, recipientInfo.recipientOtherAddress) &&
        Objects.equals(this.recipientReceivedAddress, recipientInfo.recipientReceivedAddress) &&
        Objects.equals(this.recipientSCCPAddress, recipientInfo.recipientSCCPAddress) &&
        Objects.equals(this.sMDestinationInterface, recipientInfo.sMDestinationInterface) &&
        Objects.equals(this.sMrecipientProtocolId, recipientInfo.sMrecipientProtocolId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientSUPI, recipientGPSI, recipientOtherAddress, recipientReceivedAddress, recipientSCCPAddress, sMDestinationInterface, sMrecipientProtocolId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientInfo {\n");
    
    sb.append("    recipientSUPI: ").append(toIndentedString(recipientSUPI)).append("\n");
    sb.append("    recipientGPSI: ").append(toIndentedString(recipientGPSI)).append("\n");
    sb.append("    recipientOtherAddress: ").append(toIndentedString(recipientOtherAddress)).append("\n");
    sb.append("    recipientReceivedAddress: ").append(toIndentedString(recipientReceivedAddress)).append("\n");
    sb.append("    recipientSCCPAddress: ").append(toIndentedString(recipientSCCPAddress)).append("\n");
    sb.append("    sMDestinationInterface: ").append(toIndentedString(sMDestinationInterface)).append("\n");
    sb.append("    sMrecipientProtocolId: ").append(toIndentedString(sMrecipientProtocolId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

