/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RequestedUnit
 */
@JsonPropertyOrder({
  RequestedUnit.JSON_PROPERTY_TIME,
  RequestedUnit.JSON_PROPERTY_TOTAL_VOLUME,
  RequestedUnit.JSON_PROPERTY_UPLINK_VOLUME,
  RequestedUnit.JSON_PROPERTY_DOWNLINK_VOLUME,
  RequestedUnit.JSON_PROPERTY_SERVICE_SPECIFIC_UNITS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RequestedUnit   {
  public static final String JSON_PROPERTY_TIME = "time";
  @JsonProperty(JSON_PROPERTY_TIME)
  private Integer time;

  public static final String JSON_PROPERTY_TOTAL_VOLUME = "totalVolume";
  @JsonProperty(JSON_PROPERTY_TOTAL_VOLUME)
  private Long totalVolume;

  public static final String JSON_PROPERTY_UPLINK_VOLUME = "uplinkVolume";
  @JsonProperty(JSON_PROPERTY_UPLINK_VOLUME)
  private Long uplinkVolume;

  public static final String JSON_PROPERTY_DOWNLINK_VOLUME = "downlinkVolume";
  @JsonProperty(JSON_PROPERTY_DOWNLINK_VOLUME)
  private Long downlinkVolume;

  public static final String JSON_PROPERTY_SERVICE_SPECIFIC_UNITS = "serviceSpecificUnits";
  @JsonProperty(JSON_PROPERTY_SERVICE_SPECIFIC_UNITS)
  private Long serviceSpecificUnits;

  public RequestedUnit time(Integer time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   * minimum: 0
   * @return time
   **/
  @JsonProperty(value = "time")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public RequestedUnit totalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
    return this;
  }

  /**
   * Get totalVolume
   * minimum: 0
   * @return totalVolume
   **/
  @JsonProperty(value = "totalVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getTotalVolume() {
    return totalVolume;
  }

  public void setTotalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
  }

  public RequestedUnit uplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
    return this;
  }

  /**
   * Get uplinkVolume
   * minimum: 0
   * @return uplinkVolume
   **/
  @JsonProperty(value = "uplinkVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getUplinkVolume() {
    return uplinkVolume;
  }

  public void setUplinkVolume(Long uplinkVolume) {
    this.uplinkVolume = uplinkVolume;
  }

  public RequestedUnit downlinkVolume(Long downlinkVolume) {
    this.downlinkVolume = downlinkVolume;
    return this;
  }

  /**
   * Get downlinkVolume
   * minimum: 0
   * @return downlinkVolume
   **/
  @JsonProperty(value = "downlinkVolume")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getDownlinkVolume() {
    return downlinkVolume;
  }

  public void setDownlinkVolume(Long downlinkVolume) {
    this.downlinkVolume = downlinkVolume;
  }

  public RequestedUnit serviceSpecificUnits(Long serviceSpecificUnits) {
    this.serviceSpecificUnits = serviceSpecificUnits;
    return this;
  }

  /**
   * Get serviceSpecificUnits
   * minimum: 0
   * @return serviceSpecificUnits
   **/
  @JsonProperty(value = "serviceSpecificUnits")
  @ApiModelProperty(value = "")
   @Min(0L)
  public Long getServiceSpecificUnits() {
    return serviceSpecificUnits;
  }

  public void setServiceSpecificUnits(Long serviceSpecificUnits) {
    this.serviceSpecificUnits = serviceSpecificUnits;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestedUnit requestedUnit = (RequestedUnit) o;
    return Objects.equals(this.time, requestedUnit.time) &&
        Objects.equals(this.totalVolume, requestedUnit.totalVolume) &&
        Objects.equals(this.uplinkVolume, requestedUnit.uplinkVolume) &&
        Objects.equals(this.downlinkVolume, requestedUnit.downlinkVolume) &&
        Objects.equals(this.serviceSpecificUnits, requestedUnit.serviceSpecificUnits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, totalVolume, uplinkVolume, downlinkVolume, serviceSpecificUnits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestedUnit {\n");
    
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    totalVolume: ").append(toIndentedString(totalVolume)).append("\n");
    sb.append("    uplinkVolume: ").append(toIndentedString(uplinkVolume)).append("\n");
    sb.append("    downlinkVolume: ").append(toIndentedString(downlinkVolume)).append("\n");
    sb.append("    serviceSpecificUnits: ").append(toIndentedString(serviceSpecificUnits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

