/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ResultCode
 */
public enum ResultCode {
  
  SUCCESS("SUCCESS"),
  
  END_USER_SERVICE_DENIED("END_USER_SERVICE_DENIED"),
  
  QUOTA_MANAGEMENT_NOT_APPLICABLE("QUOTA_MANAGEMENT_NOT_APPLICABLE"),
  
  QUOTA_LIMIT_REACHED("QUOTA_LIMIT_REACHED"),
  
  END_USER_SERVICE_REJECTED("END_USER_SERVICE_REJECTED"),
  
  USER_UNKNOWN("USER_UNKNOWN"),
  
  RATING_FAILED("RATING_FAILED");

  private String value;

  ResultCode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ResultCode fromValue(String value) {
    for (ResultCode b : ResultCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

