/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RoamingChargingProfile
 */
@JsonPropertyOrder({
  RoamingChargingProfile.JSON_PROPERTY_TRIGGERS,
  RoamingChargingProfile.JSON_PROPERTY_PARTIAL_RECORD_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RoamingChargingProfile   {
  public static final String JSON_PROPERTY_TRIGGERS = "triggers";
  @JsonProperty(JSON_PROPERTY_TRIGGERS)
  private List<@Valid Trigger> triggers;

  public static final String JSON_PROPERTY_PARTIAL_RECORD_METHOD = "partialRecordMethod";
  @JsonProperty(JSON_PROPERTY_PARTIAL_RECORD_METHOD)
  private PartialRecordMethod partialRecordMethod;

  public RoamingChargingProfile triggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public RoamingChargingProfile addTriggersItem(Trigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

  /**
   * Get triggers
   * @return triggers
   **/
  @JsonProperty(value = "triggers")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Trigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<@Valid Trigger> triggers) {
    this.triggers = triggers;
  }

  public RoamingChargingProfile partialRecordMethod(PartialRecordMethod partialRecordMethod) {
    this.partialRecordMethod = partialRecordMethod;
    return this;
  }

  /**
   * Get partialRecordMethod
   * @return partialRecordMethod
   **/
  @JsonProperty(value = "partialRecordMethod")
  @ApiModelProperty(value = "")
  
  public PartialRecordMethod getPartialRecordMethod() {
    return partialRecordMethod;
  }

  public void setPartialRecordMethod(PartialRecordMethod partialRecordMethod) {
    this.partialRecordMethod = partialRecordMethod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoamingChargingProfile roamingChargingProfile = (RoamingChargingProfile) o;
    return Objects.equals(this.triggers, roamingChargingProfile.triggers) &&
        Objects.equals(this.partialRecordMethod, roamingChargingProfile.partialRecordMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(triggers, partialRecordMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoamingChargingProfile {\n");
    
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    partialRecordMethod: ").append(toIndentedString(partialRecordMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

