/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SMAddressInfo
 */
@JsonPropertyOrder({
  SMAddressInfo.JSON_PROPERTY_S_MADDRESS_TYPE,
  SMAddressInfo.JSON_PROPERTY_S_MADDRESS_DATA,
  SMAddressInfo.JSON_PROPERTY_S_MADDRESS_DOMAIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class SMAddressInfo   {
  public static final String JSON_PROPERTY_S_MADDRESS_TYPE = "sMaddressType";
  @JsonProperty(JSON_PROPERTY_S_MADDRESS_TYPE)
  private SMAddressType sMaddressType;

  public static final String JSON_PROPERTY_S_MADDRESS_DATA = "sMaddressData";
  @JsonProperty(JSON_PROPERTY_S_MADDRESS_DATA)
  private String sMaddressData;

  public static final String JSON_PROPERTY_S_MADDRESS_DOMAIN = "sMaddressDomain";
  @JsonProperty(JSON_PROPERTY_S_MADDRESS_DOMAIN)
  private SMAddressDomain sMaddressDomain;

  public SMAddressInfo sMaddressType(SMAddressType sMaddressType) {
    this.sMaddressType = sMaddressType;
    return this;
  }

  /**
   * Get sMaddressType
   * @return sMaddressType
   **/
  @JsonProperty(value = "sMaddressType")
  @ApiModelProperty(value = "")
  
  public SMAddressType getsMaddressType() {
    return sMaddressType;
  }

  public void setsMaddressType(SMAddressType sMaddressType) {
    this.sMaddressType = sMaddressType;
  }

  public SMAddressInfo sMaddressData(String sMaddressData) {
    this.sMaddressData = sMaddressData;
    return this;
  }

  /**
   * Get sMaddressData
   * @return sMaddressData
   **/
  @JsonProperty(value = "sMaddressData")
  @ApiModelProperty(value = "")
  
  public String getsMaddressData() {
    return sMaddressData;
  }

  public void setsMaddressData(String sMaddressData) {
    this.sMaddressData = sMaddressData;
  }

  public SMAddressInfo sMaddressDomain(SMAddressDomain sMaddressDomain) {
    this.sMaddressDomain = sMaddressDomain;
    return this;
  }

  /**
   * Get sMaddressDomain
   * @return sMaddressDomain
   **/
  @JsonProperty(value = "sMaddressDomain")
  @ApiModelProperty(value = "")
  @Valid 
  public SMAddressDomain getsMaddressDomain() {
    return sMaddressDomain;
  }

  public void setsMaddressDomain(SMAddressDomain sMaddressDomain) {
    this.sMaddressDomain = sMaddressDomain;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMAddressInfo smAddressInfo = (SMAddressInfo) o;
    return Objects.equals(this.sMaddressType, smAddressInfo.sMaddressType) &&
        Objects.equals(this.sMaddressData, smAddressInfo.sMaddressData) &&
        Objects.equals(this.sMaddressDomain, smAddressInfo.sMaddressDomain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sMaddressType, sMaddressData, sMaddressDomain);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMAddressInfo {\n");
    
    sb.append("    sMaddressType: ").append(toIndentedString(sMaddressType)).append("\n");
    sb.append("    sMaddressData: ").append(toIndentedString(sMaddressData)).append("\n");
    sb.append("    sMaddressDomain: ").append(toIndentedString(sMaddressDomain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

