/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TriggerType
 */
public enum TriggerType {
  
  QUOTA_THRESHOLD("QUOTA_THRESHOLD"),
  
  QHT("QHT"),
  
  FINAL("FINAL"),
  
  QUOTA_EXHAUSTED("QUOTA_EXHAUSTED"),
  
  VALIDITY_TIME("VALIDITY_TIME"),
  
  OTHER_QUOTA_TYPE("OTHER_QUOTA_TYPE"),
  
  FORCED_REAUTHORISATION("FORCED_REAUTHORISATION"),
  
  UNUSED_QUOTA_TIMER("UNUSED_QUOTA_TIMER"),
  
  UNIT_COUNT_INACTIVITY_TIMER("UNIT_COUNT_INACTIVITY_TIMER"),
  
  ABNORMAL_RELEASE("ABNORMAL_RELEASE"),
  
  QOS_CHANGE("QOS_CHANGE"),
  
  VOLUME_LIMIT("VOLUME_LIMIT"),
  
  TIME_LIMIT("TIME_LIMIT"),
  
  PLMN_CHANGE("PLMN_CHANGE"),
  
  USER_LOCATION_CHANGE("USER_LOCATION_CHANGE"),
  
  RAT_CHANGE("RAT_CHANGE"),
  
  SESSION_AMBR_CHANGE("SESSION_AMBR_CHANGE"),
  
  UE_TIMEZONE_CHANGE("UE_TIMEZONE_CHANGE"),
  
  TARIFF_TIME_CHANGE("TARIFF_TIME_CHANGE"),
  
  MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS("MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS"),
  
  MANAGEMENT_INTERVENTION("MANAGEMENT_INTERVENTION"),
  
  CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA("CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA"),
  
  CHANGE_OF_3_GPP_PS_DATA_OFF_STATUS("CHANGE_OF_3GPP_PS_DATA_OFF_STATUS"),
  
  SERVING_NODE_CHANGE("SERVING_NODE_CHANGE"),
  
  REMOVAL_OF_UPF("REMOVAL_OF_UPF"),
  
  ADDITION_OF_UPF("ADDITION_OF_UPF"),
  
  START_OF_SERVICE_DATA_FLOW("START_OF_SERVICE_DATA_FLOW"),
  
  GFBR_GUARANTEED_STATUS_CHANGE("GFBR_GUARANTEED_STATUS_CHANGE");

  private String value;

  TriggerType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TriggerType fromValue(String value) {
    for (TriggerType b : TriggerType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

