/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel15.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * UserInformation
 */
@JsonPropertyOrder({
  UserInformation.JSON_PROPERTY_SERVED_G_P_S_I,
  UserInformation.JSON_PROPERTY_SERVED_P_E_I,
  UserInformation.JSON_PROPERTY_UNAUTHENTICATED_FLAG,
  UserInformation.JSON_PROPERTY_ROAMER_IN_OUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-17T08:24:27.361349500+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class UserInformation   {
  public static final String JSON_PROPERTY_SERVED_G_P_S_I = "servedGPSI";
  @JsonProperty(JSON_PROPERTY_SERVED_G_P_S_I)
  private String servedGPSI;

  public static final String JSON_PROPERTY_SERVED_P_E_I = "servedPEI";
  @JsonProperty(JSON_PROPERTY_SERVED_P_E_I)
  private String servedPEI;

  public static final String JSON_PROPERTY_UNAUTHENTICATED_FLAG = "unauthenticatedFlag";
  @JsonProperty(JSON_PROPERTY_UNAUTHENTICATED_FLAG)
  private Boolean unauthenticatedFlag;

  public static final String JSON_PROPERTY_ROAMER_IN_OUT = "roamerInOut";
  @JsonProperty(JSON_PROPERTY_ROAMER_IN_OUT)
  private RoamerInOut roamerInOut;

  public UserInformation servedGPSI(String servedGPSI) {
    this.servedGPSI = servedGPSI;
    return this;
  }

  /**
   * Get servedGPSI
   * @return servedGPSI
   **/
  @JsonProperty(value = "servedGPSI")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$")
  public String getServedGPSI() {
    return servedGPSI;
  }

  public void setServedGPSI(String servedGPSI) {
    this.servedGPSI = servedGPSI;
  }

  public UserInformation servedPEI(String servedPEI) {
    this.servedPEI = servedPEI;
    return this;
  }

  /**
   * Get servedPEI
   * @return servedPEI
   **/
  @JsonProperty(value = "servedPEI")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$")
  public String getServedPEI() {
    return servedPEI;
  }

  public void setServedPEI(String servedPEI) {
    this.servedPEI = servedPEI;
  }

  public UserInformation unauthenticatedFlag(Boolean unauthenticatedFlag) {
    this.unauthenticatedFlag = unauthenticatedFlag;
    return this;
  }

  /**
   * Get unauthenticatedFlag
   * @return unauthenticatedFlag
   **/
  @JsonProperty(value = "unauthenticatedFlag")
  @ApiModelProperty(value = "")
  
  public Boolean getUnauthenticatedFlag() {
    return unauthenticatedFlag;
  }

  public void setUnauthenticatedFlag(Boolean unauthenticatedFlag) {
    this.unauthenticatedFlag = unauthenticatedFlag;
  }

  public UserInformation roamerInOut(RoamerInOut roamerInOut) {
    this.roamerInOut = roamerInOut;
    return this;
  }

  /**
   * Get roamerInOut
   * @return roamerInOut
   **/
  @JsonProperty(value = "roamerInOut")
  @ApiModelProperty(value = "")
  
  public RoamerInOut getRoamerInOut() {
    return roamerInOut;
  }

  public void setRoamerInOut(RoamerInOut roamerInOut) {
    this.roamerInOut = roamerInOut;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInformation userInformation = (UserInformation) o;
    return Objects.equals(this.servedGPSI, userInformation.servedGPSI) &&
        Objects.equals(this.servedPEI, userInformation.servedPEI) &&
        Objects.equals(this.unauthenticatedFlag, userInformation.unauthenticatedFlag) &&
        Objects.equals(this.roamerInOut, userInformation.roamerInOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(servedGPSI, servedPEI, unauthenticatedFlag, roamerInOut);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInformation {\n");
    
    sb.append("    servedGPSI: ").append(toIndentedString(servedGPSI)).append("\n");
    sb.append("    servedPEI: ").append(toIndentedString(servedPEI)).append("\n");
    sb.append("    unauthenticatedFlag: ").append(toIndentedString(unauthenticatedFlag)).append("\n");
    sb.append("    roamerInOut: ").append(toIndentedString(roamerInOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

