/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * CellGlobalId
 */
@JsonPropertyOrder({
  CellGlobalId.JSON_PROPERTY_PLMN_ID,
  CellGlobalId.JSON_PROPERTY_LAC,
  CellGlobalId.JSON_PROPERTY_CELL_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class CellGlobalId   {
  public static final String JSON_PROPERTY_PLMN_ID = "plmnId";
  @JsonProperty(JSON_PROPERTY_PLMN_ID)
  private PlmnId plmnId;

  public static final String JSON_PROPERTY_LAC = "lac";
  @JsonProperty(JSON_PROPERTY_LAC)
  private String lac;

  public static final String JSON_PROPERTY_CELL_ID = "cellId";
  @JsonProperty(JSON_PROPERTY_CELL_ID)
  private String cellId;

  public CellGlobalId plmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
    return this;
  }

  /**
   * Get plmnId
   * @return plmnId
   **/
  @JsonProperty(value = "plmnId")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public PlmnId getPlmnId() {
    return plmnId;
  }

  public void setPlmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
  }

  public CellGlobalId lac(String lac) {
    this.lac = lac;
    return this;
  }

  /**
   * Get lac
   * @return lac
   **/
  @JsonProperty(value = "lac")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Pattern(regexp="^[A-Fa-f0-9]{4}$")
  public String getLac() {
    return lac;
  }

  public void setLac(String lac) {
    this.lac = lac;
  }

  public CellGlobalId cellId(String cellId) {
    this.cellId = cellId;
    return this;
  }

  /**
   * Get cellId
   * @return cellId
   **/
  @JsonProperty(value = "cellId")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Pattern(regexp="^[A-Fa-f0-9]{4}$")
  public String getCellId() {
    return cellId;
  }

  public void setCellId(String cellId) {
    this.cellId = cellId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellGlobalId cellGlobalId = (CellGlobalId) o;
    return Objects.equals(this.plmnId, cellGlobalId.plmnId) &&
        Objects.equals(this.lac, cellGlobalId.lac) &&
        Objects.equals(this.cellId, cellGlobalId.cellId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plmnId, lac, cellId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellGlobalId {\n");
    
    sb.append("    plmnId: ").append(toIndentedString(plmnId)).append("\n");
    sb.append("    lac: ").append(toIndentedString(lac)).append("\n");
    sb.append("    cellId: ").append(toIndentedString(cellId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

