/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ChargingNotifyResponse
 */
@JsonPropertyOrder({
  ChargingNotifyResponse.JSON_PROPERTY_INVOCATION_RESULT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class ChargingNotifyResponse   {
  public static final String JSON_PROPERTY_INVOCATION_RESULT = "invocationResult";
  @JsonProperty(JSON_PROPERTY_INVOCATION_RESULT)
  private InvocationResult invocationResult;

  public ChargingNotifyResponse invocationResult(InvocationResult invocationResult) {
    this.invocationResult = invocationResult;
    return this;
  }

  /**
   * Get invocationResult
   * @return invocationResult
   **/
  @JsonProperty(value = "invocationResult")
  @ApiModelProperty(value = "")
  @Valid 
  public InvocationResult getInvocationResult() {
    return invocationResult;
  }

  public void setInvocationResult(InvocationResult invocationResult) {
    this.invocationResult = invocationResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingNotifyResponse chargingNotifyResponse = (ChargingNotifyResponse) o;
    return Objects.equals(this.invocationResult, chargingNotifyResponse.invocationResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invocationResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingNotifyResponse {\n");
    
    sb.append("    invocationResult: ").append(toIndentedString(invocationResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

