/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * HfcNodeId
 */
@JsonPropertyOrder({
  HfcNodeId.JSON_PROPERTY_HFC_N_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class HfcNodeId   {
  public static final String JSON_PROPERTY_HFC_N_ID = "hfcNId";
  @JsonProperty(JSON_PROPERTY_HFC_N_ID)
  private String hfcNId;

  public HfcNodeId hfcNId(String hfcNId) {
    this.hfcNId = hfcNId;
    return this;
  }

  /**
   * Get hfcNId
   * @return hfcNId
   **/
  @JsonProperty(value = "hfcNId")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Size(max=6)
  public String getHfcNId() {
    return hfcNId;
  }

  public void setHfcNId(String hfcNId) {
    this.hfcNId = hfcNId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HfcNodeId hfcNodeId = (HfcNodeId) o;
    return Objects.equals(this.hfcNId, hfcNodeId.hfcNId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hfcNId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HfcNodeId {\n");
    
    sb.append("    hfcNId: ").append(toIndentedString(hfcNId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

