/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * LocationReportingChargingInformation
 */
@JsonPropertyOrder({
  LocationReportingChargingInformation.JSON_PROPERTY_LOCATION_REPORTING_MESSAGE_TYPE,
  LocationReportingChargingInformation.JSON_PROPERTY_USER_INFORMATION,
  LocationReportingChargingInformation.JSON_PROPERTY_USER_LOCATIONINFO,
  LocationReportingChargingInformation.JSON_PROPERTY_P_S_CELL_INFORMATION,
  LocationReportingChargingInformation.JSON_PROPERTY_UETIME_ZONE,
  LocationReportingChargingInformation.JSON_PROPERTY_R_A_T_TYPE,
  LocationReportingChargingInformation.JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class LocationReportingChargingInformation   {
  public static final String JSON_PROPERTY_LOCATION_REPORTING_MESSAGE_TYPE = "locationReportingMessageType";
  @JsonProperty(JSON_PROPERTY_LOCATION_REPORTING_MESSAGE_TYPE)
  private Integer locationReportingMessageType;

  public static final String JSON_PROPERTY_USER_INFORMATION = "userInformation";
  @JsonProperty(JSON_PROPERTY_USER_INFORMATION)
  private UserInformation userInformation;

  public static final String JSON_PROPERTY_USER_LOCATIONINFO = "userLocationinfo";
  @JsonProperty(JSON_PROPERTY_USER_LOCATIONINFO)
  private UserLocation userLocationinfo;

  public static final String JSON_PROPERTY_P_S_CELL_INFORMATION = "pSCellInformation";
  @JsonProperty(JSON_PROPERTY_P_S_CELL_INFORMATION)
  private PSCellInformation pSCellInformation;

  public static final String JSON_PROPERTY_UETIME_ZONE = "uetimeZone";
  @JsonProperty(JSON_PROPERTY_UETIME_ZONE)
  private String uetimeZone;

  public static final String JSON_PROPERTY_R_A_T_TYPE = "rATType";
  @JsonProperty(JSON_PROPERTY_R_A_T_TYPE)
  private RatType rATType;

  public static final String JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION = "presenceReportingAreaInformation";
  @JsonProperty(JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION)
  private Map<String, PresenceInfo> presenceReportingAreaInformation;

  public LocationReportingChargingInformation locationReportingMessageType(Integer locationReportingMessageType) {
    this.locationReportingMessageType = locationReportingMessageType;
    return this;
  }

  /**
   * Get locationReportingMessageType
   * @return locationReportingMessageType
   **/
  @JsonProperty(value = "locationReportingMessageType")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getLocationReportingMessageType() {
    return locationReportingMessageType;
  }

  public void setLocationReportingMessageType(Integer locationReportingMessageType) {
    this.locationReportingMessageType = locationReportingMessageType;
  }

  public LocationReportingChargingInformation userInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
    return this;
  }

  /**
   * Get userInformation
   * @return userInformation
   **/
  @JsonProperty(value = "userInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public UserInformation getUserInformation() {
    return userInformation;
  }

  public void setUserInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
  }

  public LocationReportingChargingInformation userLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
    return this;
  }

  /**
   * Get userLocationinfo
   * @return userLocationinfo
   **/
  @JsonProperty(value = "userLocationinfo")
  @ApiModelProperty(value = "")
  @Valid 
  public UserLocation getUserLocationinfo() {
    return userLocationinfo;
  }

  public void setUserLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
  }

  public LocationReportingChargingInformation pSCellInformation(PSCellInformation pSCellInformation) {
    this.pSCellInformation = pSCellInformation;
    return this;
  }

  /**
   * Get pSCellInformation
   * @return pSCellInformation
   **/
  @JsonProperty(value = "pSCellInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public PSCellInformation getpSCellInformation() {
    return pSCellInformation;
  }

  public void setpSCellInformation(PSCellInformation pSCellInformation) {
    this.pSCellInformation = pSCellInformation;
  }

  public LocationReportingChargingInformation uetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
    return this;
  }

  /**
   * Get uetimeZone
   * @return uetimeZone
   **/
  @JsonProperty(value = "uetimeZone")
  @ApiModelProperty(value = "")
  
  public String getUetimeZone() {
    return uetimeZone;
  }

  public void setUetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
  }

  public LocationReportingChargingInformation rATType(RatType rATType) {
    this.rATType = rATType;
    return this;
  }

  /**
   * Get rATType
   * @return rATType
   **/
  @JsonProperty(value = "rATType")
  @ApiModelProperty(value = "")
  
  public RatType getrATType() {
    return rATType;
  }

  public void setrATType(RatType rATType) {
    this.rATType = rATType;
  }

  public LocationReportingChargingInformation presenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
    return this;
  }

  public LocationReportingChargingInformation putPresenceReportingAreaInformationItem(String key, PresenceInfo presenceReportingAreaInformationItem) {
    if (this.presenceReportingAreaInformation == null) {
      this.presenceReportingAreaInformation = new HashMap<>();
    }
    this.presenceReportingAreaInformation.put(key, presenceReportingAreaInformationItem);
    return this;
  }

  /**
   * Get presenceReportingAreaInformation
   * @return presenceReportingAreaInformation
   **/
  @JsonProperty(value = "presenceReportingAreaInformation")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public Map<String, PresenceInfo> getPresenceReportingAreaInformation() {
    return presenceReportingAreaInformation;
  }

  public void setPresenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationReportingChargingInformation locationReportingChargingInformation = (LocationReportingChargingInformation) o;
    return Objects.equals(this.locationReportingMessageType, locationReportingChargingInformation.locationReportingMessageType) &&
        Objects.equals(this.userInformation, locationReportingChargingInformation.userInformation) &&
        Objects.equals(this.userLocationinfo, locationReportingChargingInformation.userLocationinfo) &&
        Objects.equals(this.pSCellInformation, locationReportingChargingInformation.pSCellInformation) &&
        Objects.equals(this.uetimeZone, locationReportingChargingInformation.uetimeZone) &&
        Objects.equals(this.rATType, locationReportingChargingInformation.rATType) &&
        Objects.equals(this.presenceReportingAreaInformation, locationReportingChargingInformation.presenceReportingAreaInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationReportingMessageType, userInformation, userLocationinfo, pSCellInformation, uetimeZone, rATType, presenceReportingAreaInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationReportingChargingInformation {\n");
    
    sb.append("    locationReportingMessageType: ").append(toIndentedString(locationReportingMessageType)).append("\n");
    sb.append("    userInformation: ").append(toIndentedString(userInformation)).append("\n");
    sb.append("    userLocationinfo: ").append(toIndentedString(userLocationinfo)).append("\n");
    sb.append("    pSCellInformation: ").append(toIndentedString(pSCellInformation)).append("\n");
    sb.append("    uetimeZone: ").append(toIndentedString(uetimeZone)).append("\n");
    sb.append("    rATType: ").append(toIndentedString(rATType)).append("\n");
    sb.append("    presenceReportingAreaInformation: ").append(toIndentedString(presenceReportingAreaInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

