/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ManagementOperation
 */
public enum ManagementOperation {
  
  CREATE_MOI("CreateMOI"),
  
  MODIFY_MOI_ATTRIBUTES("ModifyMOIAttributes"),
  
  DELETE_MOI("DeleteMOI"),
  
  CREATE_MOI2("CREATE_MOI"),
  
  MODIFY_MOI_ATTR("MODIFY_MOI_ATTR"),
  
  DELETE_MOI2("DELETE_MOI");

  private String value;

  ManagementOperation(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ManagementOperation fromValue(String value) {
    for (ManagementOperation b : ManagementOperation.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

