/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * MultipleUnitUsage
 */
@JsonPropertyOrder({
  MultipleUnitUsage.JSON_PROPERTY_RATING_GROUP,
  MultipleUnitUsage.JSON_PROPERTY_REQUESTED_UNIT,
  MultipleUnitUsage.JSON_PROPERTY_USED_UNIT_CONTAINER,
  MultipleUnitUsage.JSON_PROPERTY_U_P_F_I_D,
  MultipleUnitUsage.JSON_PROPERTY_MULTIHOMED_P_D_U_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class MultipleUnitUsage   {
  public static final String JSON_PROPERTY_RATING_GROUP = "ratingGroup";
  @JsonProperty(JSON_PROPERTY_RATING_GROUP)
  private Integer ratingGroup;

  public static final String JSON_PROPERTY_REQUESTED_UNIT = "requestedUnit";
  @JsonProperty(JSON_PROPERTY_REQUESTED_UNIT)
  private RequestedUnit requestedUnit;

  public static final String JSON_PROPERTY_USED_UNIT_CONTAINER = "usedUnitContainer";
  @JsonProperty(JSON_PROPERTY_USED_UNIT_CONTAINER)
  private List<@Valid UsedUnitContainer> usedUnitContainer;

  public static final String JSON_PROPERTY_U_P_F_I_D = "uPFID";
  @JsonProperty(JSON_PROPERTY_U_P_F_I_D)
  private UUID uPFID;

  public static final String JSON_PROPERTY_MULTIHOMED_P_D_U_ADDRESS = "multihomedPDUAddress";
  @JsonProperty(JSON_PROPERTY_MULTIHOMED_P_D_U_ADDRESS)
  private PDUAddress multihomedPDUAddress;

  public MultipleUnitUsage ratingGroup(Integer ratingGroup) {
    this.ratingGroup = ratingGroup;
    return this;
  }

  /**
   * Get ratingGroup
   * minimum: 0
   * maximum: 4294967295
   * @return ratingGroup
   **/
  @JsonProperty(value = "ratingGroup")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(0) @Max(4294967295L)
  public Integer getRatingGroup() {
    return ratingGroup;
  }

  public void setRatingGroup(Integer ratingGroup) {
    this.ratingGroup = ratingGroup;
  }

  public MultipleUnitUsage requestedUnit(RequestedUnit requestedUnit) {
    this.requestedUnit = requestedUnit;
    return this;
  }

  /**
   * Get requestedUnit
   * @return requestedUnit
   **/
  @JsonProperty(value = "requestedUnit")
  @ApiModelProperty(value = "")
  @Valid 
  public RequestedUnit getRequestedUnit() {
    return requestedUnit;
  }

  public void setRequestedUnit(RequestedUnit requestedUnit) {
    this.requestedUnit = requestedUnit;
  }

  public MultipleUnitUsage usedUnitContainer(List<@Valid UsedUnitContainer> usedUnitContainer) {
    this.usedUnitContainer = usedUnitContainer;
    return this;
  }

  public MultipleUnitUsage addUsedUnitContainerItem(UsedUnitContainer usedUnitContainerItem) {
    if (this.usedUnitContainer == null) {
      this.usedUnitContainer = new ArrayList<>();
    }
    this.usedUnitContainer.add(usedUnitContainerItem);
    return this;
  }

  /**
   * Get usedUnitContainer
   * @return usedUnitContainer
   **/
  @JsonProperty(value = "usedUnitContainer")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid UsedUnitContainer> getUsedUnitContainer() {
    return usedUnitContainer;
  }

  public void setUsedUnitContainer(List<@Valid UsedUnitContainer> usedUnitContainer) {
    this.usedUnitContainer = usedUnitContainer;
  }

  public MultipleUnitUsage uPFID(UUID uPFID) {
    this.uPFID = uPFID;
    return this;
  }

  /**
   * Get uPFID
   * @return uPFID
   **/
  @JsonProperty(value = "uPFID")
  @ApiModelProperty(value = "")
  
  public UUID getuPFID() {
    return uPFID;
  }

  public void setuPFID(UUID uPFID) {
    this.uPFID = uPFID;
  }

  public MultipleUnitUsage multihomedPDUAddress(PDUAddress multihomedPDUAddress) {
    this.multihomedPDUAddress = multihomedPDUAddress;
    return this;
  }

  /**
   * Get multihomedPDUAddress
   * @return multihomedPDUAddress
   **/
  @JsonProperty(value = "multihomedPDUAddress")
  @ApiModelProperty(value = "")
  @Valid 
  public PDUAddress getMultihomedPDUAddress() {
    return multihomedPDUAddress;
  }

  public void setMultihomedPDUAddress(PDUAddress multihomedPDUAddress) {
    this.multihomedPDUAddress = multihomedPDUAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultipleUnitUsage multipleUnitUsage = (MultipleUnitUsage) o;
    return Objects.equals(this.ratingGroup, multipleUnitUsage.ratingGroup) &&
        Objects.equals(this.requestedUnit, multipleUnitUsage.requestedUnit) &&
        Objects.equals(this.usedUnitContainer, multipleUnitUsage.usedUnitContainer) &&
        Objects.equals(this.uPFID, multipleUnitUsage.uPFID) &&
        Objects.equals(this.multihomedPDUAddress, multipleUnitUsage.multihomedPDUAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ratingGroup, requestedUnit, usedUnitContainer, uPFID, multihomedPDUAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultipleUnitUsage {\n");
    
    sb.append("    ratingGroup: ").append(toIndentedString(ratingGroup)).append("\n");
    sb.append("    requestedUnit: ").append(toIndentedString(requestedUnit)).append("\n");
    sb.append("    usedUnitContainer: ").append(toIndentedString(usedUnitContainer)).append("\n");
    sb.append("    uPFID: ").append(toIndentedString(uPFID)).append("\n");
    sb.append("    multihomedPDUAddress: ").append(toIndentedString(multihomedPDUAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

