/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * N3gaLocation
 */
@JsonPropertyOrder({
  N3gaLocation.JSON_PROPERTY_N3GPP_TAI,
  N3gaLocation.JSON_PROPERTY_N3_IWF_ID,
  N3gaLocation.JSON_PROPERTY_UE_IPV4_ADDR,
  N3gaLocation.JSON_PROPERTY_UE_IPV6_ADDR,
  N3gaLocation.JSON_PROPERTY_PORT_NUMBER,
  N3gaLocation.JSON_PROPERTY_TNAP_ID,
  N3gaLocation.JSON_PROPERTY_PROTOCOL,
  N3gaLocation.JSON_PROPERTY_TWAP_ID,
  N3gaLocation.JSON_PROPERTY_HFC_NODE_ID,
  N3gaLocation.JSON_PROPERTY_GLI,
  N3gaLocation.JSON_PROPERTY_W5GBAN_LINE_TYPE,
  N3gaLocation.JSON_PROPERTY_GCI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class N3gaLocation   {
  public static final String JSON_PROPERTY_N3GPP_TAI = "n3gppTai";
  @JsonProperty(JSON_PROPERTY_N3GPP_TAI)
  private Tai n3gppTai;

  public static final String JSON_PROPERTY_N3_IWF_ID = "n3IwfId";
  @JsonProperty(JSON_PROPERTY_N3_IWF_ID)
  private String n3IwfId;

  public static final String JSON_PROPERTY_UE_IPV4_ADDR = "ueIpv4Addr";
  @JsonProperty(JSON_PROPERTY_UE_IPV4_ADDR)
  private String ueIpv4Addr;

  public static final String JSON_PROPERTY_UE_IPV6_ADDR = "ueIpv6Addr";
  @JsonProperty(JSON_PROPERTY_UE_IPV6_ADDR)
  private Ipv6Addr ueIpv6Addr;

  public static final String JSON_PROPERTY_PORT_NUMBER = "portNumber";
  @JsonProperty(JSON_PROPERTY_PORT_NUMBER)
  private Integer portNumber;

  public static final String JSON_PROPERTY_TNAP_ID = "tnapId";
  @JsonProperty(JSON_PROPERTY_TNAP_ID)
  private TnapId tnapId;

  public static final String JSON_PROPERTY_PROTOCOL = "protocol";
  @JsonProperty(JSON_PROPERTY_PROTOCOL)
  private TransportProtocol protocol;

  public static final String JSON_PROPERTY_TWAP_ID = "twapId";
  @JsonProperty(JSON_PROPERTY_TWAP_ID)
  private TwapId twapId;

  public static final String JSON_PROPERTY_HFC_NODE_ID = "hfcNodeId";
  @JsonProperty(JSON_PROPERTY_HFC_NODE_ID)
  private HfcNodeId hfcNodeId;

  public static final String JSON_PROPERTY_GLI = "gli";
  @JsonProperty(JSON_PROPERTY_GLI)
  private byte[] gli;

  public static final String JSON_PROPERTY_W5GBAN_LINE_TYPE = "w5gbanLineType";
  @JsonProperty(JSON_PROPERTY_W5GBAN_LINE_TYPE)
  private LineType w5gbanLineType;

  public static final String JSON_PROPERTY_GCI = "gci";
  @JsonProperty(JSON_PROPERTY_GCI)
  private String gci;

  public N3gaLocation n3gppTai(Tai n3gppTai) {
    this.n3gppTai = n3gppTai;
    return this;
  }

  /**
   * Get n3gppTai
   * @return n3gppTai
   **/
  @JsonProperty(value = "n3gppTai")
  @ApiModelProperty(value = "")
  @Valid 
  public Tai getN3gppTai() {
    return n3gppTai;
  }

  public void setN3gppTai(Tai n3gppTai) {
    this.n3gppTai = n3gppTai;
  }

  public N3gaLocation n3IwfId(String n3IwfId) {
    this.n3IwfId = n3IwfId;
    return this;
  }

  /**
   * Get n3IwfId
   * @return n3IwfId
   **/
  @JsonProperty(value = "n3IwfId")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^[A-Fa-f0-9]+$")
  public String getN3IwfId() {
    return n3IwfId;
  }

  public void setN3IwfId(String n3IwfId) {
    this.n3IwfId = n3IwfId;
  }

  public N3gaLocation ueIpv4Addr(String ueIpv4Addr) {
    this.ueIpv4Addr = ueIpv4Addr;
    return this;
  }

  /**
   * Get ueIpv4Addr
   * @return ueIpv4Addr
   **/
  @JsonProperty(value = "ueIpv4Addr")
  @ApiModelProperty(example = "198.51.100.1", value = "")
   @Pattern(regexp="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$")
  public String getUeIpv4Addr() {
    return ueIpv4Addr;
  }

  public void setUeIpv4Addr(String ueIpv4Addr) {
    this.ueIpv4Addr = ueIpv4Addr;
  }

  public N3gaLocation ueIpv6Addr(Ipv6Addr ueIpv6Addr) {
    this.ueIpv6Addr = ueIpv6Addr;
    return this;
  }

  /**
   * Get ueIpv6Addr
   * @return ueIpv6Addr
   **/
  @JsonProperty(value = "ueIpv6Addr")
  @ApiModelProperty(value = "")
  @Valid 
  public Ipv6Addr getUeIpv6Addr() {
    return ueIpv6Addr;
  }

  public void setUeIpv6Addr(Ipv6Addr ueIpv6Addr) {
    this.ueIpv6Addr = ueIpv6Addr;
  }

  public N3gaLocation portNumber(Integer portNumber) {
    this.portNumber = portNumber;
    return this;
  }

  /**
   * Get portNumber
   * minimum: 0
   * @return portNumber
   **/
  @JsonProperty(value = "portNumber")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer getPortNumber() {
    return portNumber;
  }

  public void setPortNumber(Integer portNumber) {
    this.portNumber = portNumber;
  }

  public N3gaLocation tnapId(TnapId tnapId) {
    this.tnapId = tnapId;
    return this;
  }

  /**
   * Get tnapId
   * @return tnapId
   **/
  @JsonProperty(value = "tnapId")
  @ApiModelProperty(value = "")
  @Valid 
  public TnapId getTnapId() {
    return tnapId;
  }

  public void setTnapId(TnapId tnapId) {
    this.tnapId = tnapId;
  }

  public N3gaLocation protocol(TransportProtocol protocol) {
    this.protocol = protocol;
    return this;
  }

  /**
   * Get protocol
   * @return protocol
   **/
  @JsonProperty(value = "protocol")
  @ApiModelProperty(value = "")
  
  public TransportProtocol getProtocol() {
    return protocol;
  }

  public void setProtocol(TransportProtocol protocol) {
    this.protocol = protocol;
  }

  public N3gaLocation twapId(TwapId twapId) {
    this.twapId = twapId;
    return this;
  }

  /**
   * Get twapId
   * @return twapId
   **/
  @JsonProperty(value = "twapId")
  @ApiModelProperty(value = "")
  @Valid 
  public TwapId getTwapId() {
    return twapId;
  }

  public void setTwapId(TwapId twapId) {
    this.twapId = twapId;
  }

  public N3gaLocation hfcNodeId(HfcNodeId hfcNodeId) {
    this.hfcNodeId = hfcNodeId;
    return this;
  }

  /**
   * Get hfcNodeId
   * @return hfcNodeId
   **/
  @JsonProperty(value = "hfcNodeId")
  @ApiModelProperty(value = "")
  @Valid 
  public HfcNodeId getHfcNodeId() {
    return hfcNodeId;
  }

  public void setHfcNodeId(HfcNodeId hfcNodeId) {
    this.hfcNodeId = hfcNodeId;
  }

  public N3gaLocation gli(byte[] gli) {
    this.gli = gli;
    return this;
  }

  /**
   * Get gli
   * @return gli
   **/
  @JsonProperty(value = "gli")
  @ApiModelProperty(value = "")
  
  public byte[] getGli() {
    return gli;
  }

  public void setGli(byte[] gli) {
    this.gli = gli;
  }

  public N3gaLocation w5gbanLineType(LineType w5gbanLineType) {
    this.w5gbanLineType = w5gbanLineType;
    return this;
  }

  /**
   * Get w5gbanLineType
   * @return w5gbanLineType
   **/
  @JsonProperty(value = "w5gbanLineType")
  @ApiModelProperty(value = "")
  
  public LineType getW5gbanLineType() {
    return w5gbanLineType;
  }

  public void setW5gbanLineType(LineType w5gbanLineType) {
    this.w5gbanLineType = w5gbanLineType;
  }

  public N3gaLocation gci(String gci) {
    this.gci = gci;
    return this;
  }

  /**
   * Get gci
   * @return gci
   **/
  @JsonProperty(value = "gci")
  @ApiModelProperty(value = "")
  
  public String getGci() {
    return gci;
  }

  public void setGci(String gci) {
    this.gci = gci;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    N3gaLocation n3gaLocation = (N3gaLocation) o;
    return Objects.equals(this.n3gppTai, n3gaLocation.n3gppTai) &&
        Objects.equals(this.n3IwfId, n3gaLocation.n3IwfId) &&
        Objects.equals(this.ueIpv4Addr, n3gaLocation.ueIpv4Addr) &&
        Objects.equals(this.ueIpv6Addr, n3gaLocation.ueIpv6Addr) &&
        Objects.equals(this.portNumber, n3gaLocation.portNumber) &&
        Objects.equals(this.tnapId, n3gaLocation.tnapId) &&
        Objects.equals(this.protocol, n3gaLocation.protocol) &&
        Objects.equals(this.twapId, n3gaLocation.twapId) &&
        Objects.equals(this.hfcNodeId, n3gaLocation.hfcNodeId) &&
        Objects.equals(this.gli, n3gaLocation.gli) &&
        Objects.equals(this.w5gbanLineType, n3gaLocation.w5gbanLineType) &&
        Objects.equals(this.gci, n3gaLocation.gci);
  }

  @Override
  public int hashCode() {
    return Objects.hash(n3gppTai, n3IwfId, ueIpv4Addr, ueIpv6Addr, portNumber, tnapId, protocol, twapId, hfcNodeId, gli, w5gbanLineType, gci);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class N3gaLocation {\n");
    
    sb.append("    n3gppTai: ").append(toIndentedString(n3gppTai)).append("\n");
    sb.append("    n3IwfId: ").append(toIndentedString(n3IwfId)).append("\n");
    sb.append("    ueIpv4Addr: ").append(toIndentedString(ueIpv4Addr)).append("\n");
    sb.append("    ueIpv6Addr: ").append(toIndentedString(ueIpv6Addr)).append("\n");
    sb.append("    portNumber: ").append(toIndentedString(portNumber)).append("\n");
    sb.append("    tnapId: ").append(toIndentedString(tnapId)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    twapId: ").append(toIndentedString(twapId)).append("\n");
    sb.append("    hfcNodeId: ").append(toIndentedString(hfcNodeId)).append("\n");
    sb.append("    gli: ").append(toIndentedString(gli)).append("\n");
    sb.append("    w5gbanLineType: ").append(toIndentedString(w5gbanLineType)).append("\n");
    sb.append("    gci: ").append(toIndentedString(gci)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

