/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets NodeFunctionality
 */
public enum NodeFunctionality {
  
  AMF("AMF"),
  
  SMF("SMF"),
  
  SMS("SMS"),
  
  SMSF("SMSF"),
  
  PGW_C_SMF("PGW_C_SMF"),
  
  NEFF("NEFF"),
  
  SGW("SGW"),
  
  I_SMF("I_SMF"),
  
  E_PDG("ePDG"),
  
  CEF("CEF"),
  
  NEF("NEF"),
  
  MN_S_PRODUCER("MnS_Producer");

  private String value;

  NodeFunctionality(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static NodeFunctionality fromValue(String value) {
    for (NodeFunctionality b : NodeFunctionality.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

