/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * NSPAChargingInformation
 */
@JsonPropertyOrder({
  NSPAChargingInformation.JSON_PROPERTY_SINGLE_N_S_S_A_I
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class NSPAChargingInformation   {
  public static final String JSON_PROPERTY_SINGLE_N_S_S_A_I = "singleNSSAI";
  @JsonProperty(JSON_PROPERTY_SINGLE_N_S_S_A_I)
  private Snssai singleNSSAI;

  public NSPAChargingInformation singleNSSAI(Snssai singleNSSAI) {
    this.singleNSSAI = singleNSSAI;
    return this;
  }

  /**
   * Get singleNSSAI
   * @return singleNSSAI
   **/
  @JsonProperty(value = "singleNSSAI")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public Snssai getSingleNSSAI() {
    return singleNSSAI;
  }

  public void setSingleNSSAI(Snssai singleNSSAI) {
    this.singleNSSAI = singleNSSAI;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NSPAChargingInformation nsPAChargingInformation = (NSPAChargingInformation) o;
    return Objects.equals(this.singleNSSAI, nsPAChargingInformation.singleNSSAI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(singleNSSAI);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NSPAChargingInformation {\n");
    
    sb.append("    singleNSSAI: ").append(toIndentedString(singleNSSAI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

