/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * PDUContainerInformation
 */
@JsonPropertyOrder({
  PDUContainerInformation.JSON_PROPERTY_TIMEOF_FIRST_USAGE,
  PDUContainerInformation.JSON_PROPERTY_TIMEOF_LAST_USAGE,
  PDUContainerInformation.JSON_PROPERTY_QO_S_INFORMATION,
  PDUContainerInformation.JSON_PROPERTY_QO_S_CHARACTERISTICS,
  PDUContainerInformation.JSON_PROPERTY_AF_CHARGING_IDENTIFIER,
  PDUContainerInformation.JSON_PROPERTY_AF_CHARGING_ID_STRING,
  PDUContainerInformation.JSON_PROPERTY_USER_LOCATION_INFORMATION,
  PDUContainerInformation.JSON_PROPERTY_UETIME_ZONE,
  PDUContainerInformation.JSON_PROPERTY_R_A_T_TYPE,
  PDUContainerInformation.JSON_PROPERTY_SERVING_NODE_I_D,
  PDUContainerInformation.JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION,
  PDUContainerInformation.JSON_PROPERTY_3GPP_P_S_DATA_OFF_STATUS,
  PDUContainerInformation.JSON_PROPERTY_SPONSOR_IDENTITY,
  PDUContainerInformation.JSON_PROPERTY_APPLICATIONSERVICE_PROVIDER_IDENTITY,
  PDUContainerInformation.JSON_PROPERTY_CHARGING_RULE_BASE_NAME,
  PDUContainerInformation.JSON_PROPERTY_M_A_P_D_U_STEERING_FUNCTIONALITY,
  PDUContainerInformation.JSON_PROPERTY_M_A_P_D_U_STEERING_MODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class PDUContainerInformation   {
  public static final String JSON_PROPERTY_TIMEOF_FIRST_USAGE = "timeofFirstUsage";
  @JsonProperty(JSON_PROPERTY_TIMEOF_FIRST_USAGE)
  private Date timeofFirstUsage;

  public static final String JSON_PROPERTY_TIMEOF_LAST_USAGE = "timeofLastUsage";
  @JsonProperty(JSON_PROPERTY_TIMEOF_LAST_USAGE)
  private Date timeofLastUsage;

  public static final String JSON_PROPERTY_QO_S_INFORMATION = "qoSInformation";
  @JsonProperty(JSON_PROPERTY_QO_S_INFORMATION)
  private QosData qoSInformation;

  public static final String JSON_PROPERTY_QO_S_CHARACTERISTICS = "qoSCharacteristics";
  @JsonProperty(JSON_PROPERTY_QO_S_CHARACTERISTICS)
  private QosCharacteristics qoSCharacteristics;

  public static final String JSON_PROPERTY_AF_CHARGING_IDENTIFIER = "afChargingIdentifier";
  @JsonProperty(JSON_PROPERTY_AF_CHARGING_IDENTIFIER)
  private Integer afChargingIdentifier;

  public static final String JSON_PROPERTY_AF_CHARGING_ID_STRING = "afChargingIdString";
  @JsonProperty(JSON_PROPERTY_AF_CHARGING_ID_STRING)
  private String afChargingIdString;

  public static final String JSON_PROPERTY_USER_LOCATION_INFORMATION = "userLocationInformation";
  @JsonProperty(JSON_PROPERTY_USER_LOCATION_INFORMATION)
  private UserLocation userLocationInformation;

  public static final String JSON_PROPERTY_UETIME_ZONE = "uetimeZone";
  @JsonProperty(JSON_PROPERTY_UETIME_ZONE)
  private String uetimeZone;

  public static final String JSON_PROPERTY_R_A_T_TYPE = "rATType";
  @JsonProperty(JSON_PROPERTY_R_A_T_TYPE)
  private RatType rATType;

  public static final String JSON_PROPERTY_SERVING_NODE_I_D = "servingNodeID";
  @JsonProperty(JSON_PROPERTY_SERVING_NODE_I_D)
  private List<@Valid ServingNetworkFunctionID> servingNodeID;

  public static final String JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION = "presenceReportingAreaInformation";
  @JsonProperty(JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION)
  private Map<String, PresenceInfo> presenceReportingAreaInformation;

  public static final String JSON_PROPERTY_3GPP_P_S_DATA_OFF_STATUS = "3gppPSDataOffStatus";
  @JsonProperty(JSON_PROPERTY_3GPP_P_S_DATA_OFF_STATUS)
  private Model3GPPPSDataOffStatus _3gppPSDataOffStatus;

  public static final String JSON_PROPERTY_SPONSOR_IDENTITY = "sponsorIdentity";
  @JsonProperty(JSON_PROPERTY_SPONSOR_IDENTITY)
  private String sponsorIdentity;

  public static final String JSON_PROPERTY_APPLICATIONSERVICE_PROVIDER_IDENTITY = "applicationserviceProviderIdentity";
  @JsonProperty(JSON_PROPERTY_APPLICATIONSERVICE_PROVIDER_IDENTITY)
  private String applicationserviceProviderIdentity;

  public static final String JSON_PROPERTY_CHARGING_RULE_BASE_NAME = "chargingRuleBaseName";
  @JsonProperty(JSON_PROPERTY_CHARGING_RULE_BASE_NAME)
  private String chargingRuleBaseName;

  public static final String JSON_PROPERTY_M_A_P_D_U_STEERING_FUNCTIONALITY = "mAPDUSteeringFunctionality";
  @JsonProperty(JSON_PROPERTY_M_A_P_D_U_STEERING_FUNCTIONALITY)
  private SteeringFunctionality mAPDUSteeringFunctionality;

  public static final String JSON_PROPERTY_M_A_P_D_U_STEERING_MODE = "mAPDUSteeringMode";
  @JsonProperty(JSON_PROPERTY_M_A_P_D_U_STEERING_MODE)
  private SteeringMode mAPDUSteeringMode;

  public PDUContainerInformation timeofFirstUsage(Date timeofFirstUsage) {
    this.timeofFirstUsage = timeofFirstUsage;
    return this;
  }

  /**
   * Get timeofFirstUsage
   * @return timeofFirstUsage
   **/
  @JsonProperty(value = "timeofFirstUsage")
  @ApiModelProperty(value = "")
  
  public Date getTimeofFirstUsage() {
    return timeofFirstUsage;
  }

  public void setTimeofFirstUsage(Date timeofFirstUsage) {
    this.timeofFirstUsage = timeofFirstUsage;
  }

  public PDUContainerInformation timeofLastUsage(Date timeofLastUsage) {
    this.timeofLastUsage = timeofLastUsage;
    return this;
  }

  /**
   * Get timeofLastUsage
   * @return timeofLastUsage
   **/
  @JsonProperty(value = "timeofLastUsage")
  @ApiModelProperty(value = "")
  
  public Date getTimeofLastUsage() {
    return timeofLastUsage;
  }

  public void setTimeofLastUsage(Date timeofLastUsage) {
    this.timeofLastUsage = timeofLastUsage;
  }

  public PDUContainerInformation qoSInformation(QosData qoSInformation) {
    this.qoSInformation = qoSInformation;
    return this;
  }

  /**
   * Get qoSInformation
   * @return qoSInformation
   **/
  @JsonProperty(value = "qoSInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public QosData getQoSInformation() {
    return qoSInformation;
  }

  public void setQoSInformation(QosData qoSInformation) {
    this.qoSInformation = qoSInformation;
  }

  public PDUContainerInformation qoSCharacteristics(QosCharacteristics qoSCharacteristics) {
    this.qoSCharacteristics = qoSCharacteristics;
    return this;
  }

  /**
   * Get qoSCharacteristics
   * @return qoSCharacteristics
   **/
  @JsonProperty(value = "qoSCharacteristics")
  @ApiModelProperty(value = "")
  @Valid 
  public QosCharacteristics getQoSCharacteristics() {
    return qoSCharacteristics;
  }

  public void setQoSCharacteristics(QosCharacteristics qoSCharacteristics) {
    this.qoSCharacteristics = qoSCharacteristics;
  }

  public PDUContainerInformation afChargingIdentifier(Integer afChargingIdentifier) {
    this.afChargingIdentifier = afChargingIdentifier;
    return this;
  }

  /**
   * Get afChargingIdentifier
   * minimum: 0
   * maximum: 4294967295
   * @return afChargingIdentifier
   **/
  @JsonProperty(value = "afChargingIdentifier")
  @ApiModelProperty(value = "")
   @Min(0) @Max(4294967295L)
  public Integer getAfChargingIdentifier() {
    return afChargingIdentifier;
  }

  public void setAfChargingIdentifier(Integer afChargingIdentifier) {
    this.afChargingIdentifier = afChargingIdentifier;
  }

  public PDUContainerInformation afChargingIdString(String afChargingIdString) {
    this.afChargingIdString = afChargingIdString;
    return this;
  }

  /**
   * Get afChargingIdString
   * @return afChargingIdString
   **/
  @JsonProperty(value = "afChargingIdString")
  @ApiModelProperty(value = "")
  
  public String getAfChargingIdString() {
    return afChargingIdString;
  }

  public void setAfChargingIdString(String afChargingIdString) {
    this.afChargingIdString = afChargingIdString;
  }

  public PDUContainerInformation userLocationInformation(UserLocation userLocationInformation) {
    this.userLocationInformation = userLocationInformation;
    return this;
  }

  /**
   * Get userLocationInformation
   * @return userLocationInformation
   **/
  @JsonProperty(value = "userLocationInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public UserLocation getUserLocationInformation() {
    return userLocationInformation;
  }

  public void setUserLocationInformation(UserLocation userLocationInformation) {
    this.userLocationInformation = userLocationInformation;
  }

  public PDUContainerInformation uetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
    return this;
  }

  /**
   * Get uetimeZone
   * @return uetimeZone
   **/
  @JsonProperty(value = "uetimeZone")
  @ApiModelProperty(value = "")
  
  public String getUetimeZone() {
    return uetimeZone;
  }

  public void setUetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
  }

  public PDUContainerInformation rATType(RatType rATType) {
    this.rATType = rATType;
    return this;
  }

  /**
   * Get rATType
   * @return rATType
   **/
  @JsonProperty(value = "rATType")
  @ApiModelProperty(value = "")
  
  public RatType getrATType() {
    return rATType;
  }

  public void setrATType(RatType rATType) {
    this.rATType = rATType;
  }

  public PDUContainerInformation servingNodeID(List<@Valid ServingNetworkFunctionID> servingNodeID) {
    this.servingNodeID = servingNodeID;
    return this;
  }

  public PDUContainerInformation addServingNodeIDItem(ServingNetworkFunctionID servingNodeIDItem) {
    if (this.servingNodeID == null) {
      this.servingNodeID = new ArrayList<>();
    }
    this.servingNodeID.add(servingNodeIDItem);
    return this;
  }

  /**
   * Get servingNodeID
   * @return servingNodeID
   **/
  @JsonProperty(value = "servingNodeID")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid ServingNetworkFunctionID> getServingNodeID() {
    return servingNodeID;
  }

  public void setServingNodeID(List<@Valid ServingNetworkFunctionID> servingNodeID) {
    this.servingNodeID = servingNodeID;
  }

  public PDUContainerInformation presenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
    return this;
  }

  public PDUContainerInformation putPresenceReportingAreaInformationItem(String key, PresenceInfo presenceReportingAreaInformationItem) {
    if (this.presenceReportingAreaInformation == null) {
      this.presenceReportingAreaInformation = new HashMap<>();
    }
    this.presenceReportingAreaInformation.put(key, presenceReportingAreaInformationItem);
    return this;
  }

  /**
   * Get presenceReportingAreaInformation
   * @return presenceReportingAreaInformation
   **/
  @JsonProperty(value = "presenceReportingAreaInformation")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public Map<String, PresenceInfo> getPresenceReportingAreaInformation() {
    return presenceReportingAreaInformation;
  }

  public void setPresenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
  }

  public PDUContainerInformation _3gppPSDataOffStatus(Model3GPPPSDataOffStatus _3gppPSDataOffStatus) {
    this._3gppPSDataOffStatus = _3gppPSDataOffStatus;
    return this;
  }

  /**
   * Get _3gppPSDataOffStatus
   * @return _3gppPSDataOffStatus
   **/
  @JsonProperty(value = "3gppPSDataOffStatus")
  @ApiModelProperty(value = "")
  
  public Model3GPPPSDataOffStatus get3gppPSDataOffStatus() {
    return _3gppPSDataOffStatus;
  }

  public void set3gppPSDataOffStatus(Model3GPPPSDataOffStatus _3gppPSDataOffStatus) {
    this._3gppPSDataOffStatus = _3gppPSDataOffStatus;
  }

  public PDUContainerInformation sponsorIdentity(String sponsorIdentity) {
    this.sponsorIdentity = sponsorIdentity;
    return this;
  }

  /**
   * Get sponsorIdentity
   * @return sponsorIdentity
   **/
  @JsonProperty(value = "sponsorIdentity")
  @ApiModelProperty(value = "")
  
  public String getSponsorIdentity() {
    return sponsorIdentity;
  }

  public void setSponsorIdentity(String sponsorIdentity) {
    this.sponsorIdentity = sponsorIdentity;
  }

  public PDUContainerInformation applicationserviceProviderIdentity(String applicationserviceProviderIdentity) {
    this.applicationserviceProviderIdentity = applicationserviceProviderIdentity;
    return this;
  }

  /**
   * Get applicationserviceProviderIdentity
   * @return applicationserviceProviderIdentity
   **/
  @JsonProperty(value = "applicationserviceProviderIdentity")
  @ApiModelProperty(value = "")
  
  public String getApplicationserviceProviderIdentity() {
    return applicationserviceProviderIdentity;
  }

  public void setApplicationserviceProviderIdentity(String applicationserviceProviderIdentity) {
    this.applicationserviceProviderIdentity = applicationserviceProviderIdentity;
  }

  public PDUContainerInformation chargingRuleBaseName(String chargingRuleBaseName) {
    this.chargingRuleBaseName = chargingRuleBaseName;
    return this;
  }

  /**
   * Get chargingRuleBaseName
   * @return chargingRuleBaseName
   **/
  @JsonProperty(value = "chargingRuleBaseName")
  @ApiModelProperty(value = "")
  
  public String getChargingRuleBaseName() {
    return chargingRuleBaseName;
  }

  public void setChargingRuleBaseName(String chargingRuleBaseName) {
    this.chargingRuleBaseName = chargingRuleBaseName;
  }

  public PDUContainerInformation mAPDUSteeringFunctionality(SteeringFunctionality mAPDUSteeringFunctionality) {
    this.mAPDUSteeringFunctionality = mAPDUSteeringFunctionality;
    return this;
  }

  /**
   * Get mAPDUSteeringFunctionality
   * @return mAPDUSteeringFunctionality
   **/
  @JsonProperty(value = "mAPDUSteeringFunctionality")
  @ApiModelProperty(value = "")
  
  public SteeringFunctionality getmAPDUSteeringFunctionality() {
    return mAPDUSteeringFunctionality;
  }

  public void setmAPDUSteeringFunctionality(SteeringFunctionality mAPDUSteeringFunctionality) {
    this.mAPDUSteeringFunctionality = mAPDUSteeringFunctionality;
  }

  public PDUContainerInformation mAPDUSteeringMode(SteeringMode mAPDUSteeringMode) {
    this.mAPDUSteeringMode = mAPDUSteeringMode;
    return this;
  }

  /**
   * Get mAPDUSteeringMode
   * @return mAPDUSteeringMode
   **/
  @JsonProperty(value = "mAPDUSteeringMode")
  @ApiModelProperty(value = "")
  @Valid 
  public SteeringMode getmAPDUSteeringMode() {
    return mAPDUSteeringMode;
  }

  public void setmAPDUSteeringMode(SteeringMode mAPDUSteeringMode) {
    this.mAPDUSteeringMode = mAPDUSteeringMode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDUContainerInformation pdUContainerInformation = (PDUContainerInformation) o;
    return Objects.equals(this.timeofFirstUsage, pdUContainerInformation.timeofFirstUsage) &&
        Objects.equals(this.timeofLastUsage, pdUContainerInformation.timeofLastUsage) &&
        Objects.equals(this.qoSInformation, pdUContainerInformation.qoSInformation) &&
        Objects.equals(this.qoSCharacteristics, pdUContainerInformation.qoSCharacteristics) &&
        Objects.equals(this.afChargingIdentifier, pdUContainerInformation.afChargingIdentifier) &&
        Objects.equals(this.afChargingIdString, pdUContainerInformation.afChargingIdString) &&
        Objects.equals(this.userLocationInformation, pdUContainerInformation.userLocationInformation) &&
        Objects.equals(this.uetimeZone, pdUContainerInformation.uetimeZone) &&
        Objects.equals(this.rATType, pdUContainerInformation.rATType) &&
        Objects.equals(this.servingNodeID, pdUContainerInformation.servingNodeID) &&
        Objects.equals(this.presenceReportingAreaInformation, pdUContainerInformation.presenceReportingAreaInformation) &&
        Objects.equals(this._3gppPSDataOffStatus, pdUContainerInformation._3gppPSDataOffStatus) &&
        Objects.equals(this.sponsorIdentity, pdUContainerInformation.sponsorIdentity) &&
        Objects.equals(this.applicationserviceProviderIdentity, pdUContainerInformation.applicationserviceProviderIdentity) &&
        Objects.equals(this.chargingRuleBaseName, pdUContainerInformation.chargingRuleBaseName) &&
        Objects.equals(this.mAPDUSteeringFunctionality, pdUContainerInformation.mAPDUSteeringFunctionality) &&
        Objects.equals(this.mAPDUSteeringMode, pdUContainerInformation.mAPDUSteeringMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeofFirstUsage, timeofLastUsage, qoSInformation, qoSCharacteristics, afChargingIdentifier, afChargingIdString, userLocationInformation, uetimeZone, rATType, servingNodeID, presenceReportingAreaInformation, _3gppPSDataOffStatus, sponsorIdentity, applicationserviceProviderIdentity, chargingRuleBaseName, mAPDUSteeringFunctionality, mAPDUSteeringMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDUContainerInformation {\n");
    
    sb.append("    timeofFirstUsage: ").append(toIndentedString(timeofFirstUsage)).append("\n");
    sb.append("    timeofLastUsage: ").append(toIndentedString(timeofLastUsage)).append("\n");
    sb.append("    qoSInformation: ").append(toIndentedString(qoSInformation)).append("\n");
    sb.append("    qoSCharacteristics: ").append(toIndentedString(qoSCharacteristics)).append("\n");
    sb.append("    afChargingIdentifier: ").append(toIndentedString(afChargingIdentifier)).append("\n");
    sb.append("    afChargingIdString: ").append(toIndentedString(afChargingIdString)).append("\n");
    sb.append("    userLocationInformation: ").append(toIndentedString(userLocationInformation)).append("\n");
    sb.append("    uetimeZone: ").append(toIndentedString(uetimeZone)).append("\n");
    sb.append("    rATType: ").append(toIndentedString(rATType)).append("\n");
    sb.append("    servingNodeID: ").append(toIndentedString(servingNodeID)).append("\n");
    sb.append("    presenceReportingAreaInformation: ").append(toIndentedString(presenceReportingAreaInformation)).append("\n");
    sb.append("    _3gppPSDataOffStatus: ").append(toIndentedString(_3gppPSDataOffStatus)).append("\n");
    sb.append("    sponsorIdentity: ").append(toIndentedString(sponsorIdentity)).append("\n");
    sb.append("    applicationserviceProviderIdentity: ").append(toIndentedString(applicationserviceProviderIdentity)).append("\n");
    sb.append("    chargingRuleBaseName: ").append(toIndentedString(chargingRuleBaseName)).append("\n");
    sb.append("    mAPDUSteeringFunctionality: ").append(toIndentedString(mAPDUSteeringFunctionality)).append("\n");
    sb.append("    mAPDUSteeringMode: ").append(toIndentedString(mAPDUSteeringMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

