/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * PDUSessionChargingInformation
 */
@JsonPropertyOrder({
  PDUSessionChargingInformation.JSON_PROPERTY_CHARGING_ID,
  PDUSessionChargingInformation.JSON_PROPERTY_HOME_PROVIDED_CHARGING_ID,
  PDUSessionChargingInformation.JSON_PROPERTY_USER_INFORMATION,
  PDUSessionChargingInformation.JSON_PROPERTY_USER_LOCATIONINFO,
  PDUSessionChargingInformation.JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_INFO,
  PDUSessionChargingInformation.JSON_PROPERTY_NON3_G_P_P_USER_LOCATION_TIME,
  PDUSessionChargingInformation.JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_TIME,
  PDUSessionChargingInformation.JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION,
  PDUSessionChargingInformation.JSON_PROPERTY_UETIME_ZONE,
  PDUSessionChargingInformation.JSON_PROPERTY_PDU_SESSION_INFORMATION,
  PDUSessionChargingInformation.JSON_PROPERTY_UNIT_COUNT_INACTIVITY_TIMER,
  PDUSessionChargingInformation.JSON_PROPERTY_R_A_N_SECONDARY_R_A_T_USAGE_REPORT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class PDUSessionChargingInformation   {
  public static final String JSON_PROPERTY_CHARGING_ID = "chargingId";
  @JsonProperty(JSON_PROPERTY_CHARGING_ID)
  private Integer chargingId;

  public static final String JSON_PROPERTY_HOME_PROVIDED_CHARGING_ID = "homeProvidedChargingId";
  @JsonProperty(JSON_PROPERTY_HOME_PROVIDED_CHARGING_ID)
  private Integer homeProvidedChargingId;

  public static final String JSON_PROPERTY_USER_INFORMATION = "userInformation";
  @JsonProperty(JSON_PROPERTY_USER_INFORMATION)
  private UserInformation userInformation;

  public static final String JSON_PROPERTY_USER_LOCATIONINFO = "userLocationinfo";
  @JsonProperty(JSON_PROPERTY_USER_LOCATIONINFO)
  private UserLocation userLocationinfo;

  public static final String JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_INFO = "mAPDUNon3GPPUserLocationInfo";
  @JsonProperty(JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_INFO)
  private UserLocation mAPDUNon3GPPUserLocationInfo;

  public static final String JSON_PROPERTY_NON3_G_P_P_USER_LOCATION_TIME = "non3GPPUserLocationTime";
  @JsonProperty(JSON_PROPERTY_NON3_G_P_P_USER_LOCATION_TIME)
  private Date non3GPPUserLocationTime;

  public static final String JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_TIME = "mAPDUNon3GPPUserLocationTime";
  @JsonProperty(JSON_PROPERTY_M_A_P_D_U_NON3_G_P_P_USER_LOCATION_TIME)
  private Date mAPDUNon3GPPUserLocationTime;

  public static final String JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION = "presenceReportingAreaInformation";
  @JsonProperty(JSON_PROPERTY_PRESENCE_REPORTING_AREA_INFORMATION)
  private Map<String, PresenceInfo> presenceReportingAreaInformation;

  public static final String JSON_PROPERTY_UETIME_ZONE = "uetimeZone";
  @JsonProperty(JSON_PROPERTY_UETIME_ZONE)
  private String uetimeZone;

  public static final String JSON_PROPERTY_PDU_SESSION_INFORMATION = "pduSessionInformation";
  @JsonProperty(JSON_PROPERTY_PDU_SESSION_INFORMATION)
  private PDUSessionInformation pduSessionInformation;

  public static final String JSON_PROPERTY_UNIT_COUNT_INACTIVITY_TIMER = "unitCountInactivityTimer";
  @JsonProperty(JSON_PROPERTY_UNIT_COUNT_INACTIVITY_TIMER)
  private Integer unitCountInactivityTimer;

  public static final String JSON_PROPERTY_R_A_N_SECONDARY_R_A_T_USAGE_REPORT = "rANSecondaryRATUsageReport";
  @JsonProperty(JSON_PROPERTY_R_A_N_SECONDARY_R_A_T_USAGE_REPORT)
  private RANSecondaryRATUsageReport rANSecondaryRATUsageReport;

  public PDUSessionChargingInformation chargingId(Integer chargingId) {
    this.chargingId = chargingId;
    return this;
  }

  /**
   * Get chargingId
   * minimum: 0
   * maximum: 4294967295
   * @return chargingId
   **/
  @JsonProperty(value = "chargingId")
  @ApiModelProperty(value = "")
   @Min(0) @Max(4294967295L)
  public Integer getChargingId() {
    return chargingId;
  }

  public void setChargingId(Integer chargingId) {
    this.chargingId = chargingId;
  }

  public PDUSessionChargingInformation homeProvidedChargingId(Integer homeProvidedChargingId) {
    this.homeProvidedChargingId = homeProvidedChargingId;
    return this;
  }

  /**
   * Get homeProvidedChargingId
   * minimum: 0
   * maximum: 4294967295
   * @return homeProvidedChargingId
   **/
  @JsonProperty(value = "homeProvidedChargingId")
  @ApiModelProperty(value = "")
   @Min(0) @Max(4294967295L)
  public Integer getHomeProvidedChargingId() {
    return homeProvidedChargingId;
  }

  public void setHomeProvidedChargingId(Integer homeProvidedChargingId) {
    this.homeProvidedChargingId = homeProvidedChargingId;
  }

  public PDUSessionChargingInformation userInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
    return this;
  }

  /**
   * Get userInformation
   * @return userInformation
   **/
  @JsonProperty(value = "userInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public UserInformation getUserInformation() {
    return userInformation;
  }

  public void setUserInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
  }

  public PDUSessionChargingInformation userLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
    return this;
  }

  /**
   * Get userLocationinfo
   * @return userLocationinfo
   **/
  @JsonProperty(value = "userLocationinfo")
  @ApiModelProperty(value = "")
  @Valid 
  public UserLocation getUserLocationinfo() {
    return userLocationinfo;
  }

  public void setUserLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
  }

  public PDUSessionChargingInformation mAPDUNon3GPPUserLocationInfo(UserLocation mAPDUNon3GPPUserLocationInfo) {
    this.mAPDUNon3GPPUserLocationInfo = mAPDUNon3GPPUserLocationInfo;
    return this;
  }

  /**
   * Get mAPDUNon3GPPUserLocationInfo
   * @return mAPDUNon3GPPUserLocationInfo
   **/
  @JsonProperty(value = "mAPDUNon3GPPUserLocationInfo")
  @ApiModelProperty(value = "")
  @Valid 
  public UserLocation getmAPDUNon3GPPUserLocationInfo() {
    return mAPDUNon3GPPUserLocationInfo;
  }

  public void setmAPDUNon3GPPUserLocationInfo(UserLocation mAPDUNon3GPPUserLocationInfo) {
    this.mAPDUNon3GPPUserLocationInfo = mAPDUNon3GPPUserLocationInfo;
  }

  public PDUSessionChargingInformation non3GPPUserLocationTime(Date non3GPPUserLocationTime) {
    this.non3GPPUserLocationTime = non3GPPUserLocationTime;
    return this;
  }

  /**
   * Get non3GPPUserLocationTime
   * @return non3GPPUserLocationTime
   **/
  @JsonProperty(value = "non3GPPUserLocationTime")
  @ApiModelProperty(value = "")
  
  public Date getNon3GPPUserLocationTime() {
    return non3GPPUserLocationTime;
  }

  public void setNon3GPPUserLocationTime(Date non3GPPUserLocationTime) {
    this.non3GPPUserLocationTime = non3GPPUserLocationTime;
  }

  public PDUSessionChargingInformation mAPDUNon3GPPUserLocationTime(Date mAPDUNon3GPPUserLocationTime) {
    this.mAPDUNon3GPPUserLocationTime = mAPDUNon3GPPUserLocationTime;
    return this;
  }

  /**
   * Get mAPDUNon3GPPUserLocationTime
   * @return mAPDUNon3GPPUserLocationTime
   **/
  @JsonProperty(value = "mAPDUNon3GPPUserLocationTime")
  @ApiModelProperty(value = "")
  
  public Date getmAPDUNon3GPPUserLocationTime() {
    return mAPDUNon3GPPUserLocationTime;
  }

  public void setmAPDUNon3GPPUserLocationTime(Date mAPDUNon3GPPUserLocationTime) {
    this.mAPDUNon3GPPUserLocationTime = mAPDUNon3GPPUserLocationTime;
  }

  public PDUSessionChargingInformation presenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
    return this;
  }

  public PDUSessionChargingInformation putPresenceReportingAreaInformationItem(String key, PresenceInfo presenceReportingAreaInformationItem) {
    if (this.presenceReportingAreaInformation == null) {
      this.presenceReportingAreaInformation = new HashMap<>();
    }
    this.presenceReportingAreaInformation.put(key, presenceReportingAreaInformationItem);
    return this;
  }

  /**
   * Get presenceReportingAreaInformation
   * @return presenceReportingAreaInformation
   **/
  @JsonProperty(value = "presenceReportingAreaInformation")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public Map<String, PresenceInfo> getPresenceReportingAreaInformation() {
    return presenceReportingAreaInformation;
  }

  public void setPresenceReportingAreaInformation(Map<String, PresenceInfo> presenceReportingAreaInformation) {
    this.presenceReportingAreaInformation = presenceReportingAreaInformation;
  }

  public PDUSessionChargingInformation uetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
    return this;
  }

  /**
   * Get uetimeZone
   * @return uetimeZone
   **/
  @JsonProperty(value = "uetimeZone")
  @ApiModelProperty(value = "")
  
  public String getUetimeZone() {
    return uetimeZone;
  }

  public void setUetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
  }

  public PDUSessionChargingInformation pduSessionInformation(PDUSessionInformation pduSessionInformation) {
    this.pduSessionInformation = pduSessionInformation;
    return this;
  }

  /**
   * Get pduSessionInformation
   * @return pduSessionInformation
   **/
  @JsonProperty(value = "pduSessionInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public PDUSessionInformation getPduSessionInformation() {
    return pduSessionInformation;
  }

  public void setPduSessionInformation(PDUSessionInformation pduSessionInformation) {
    this.pduSessionInformation = pduSessionInformation;
  }

  public PDUSessionChargingInformation unitCountInactivityTimer(Integer unitCountInactivityTimer) {
    this.unitCountInactivityTimer = unitCountInactivityTimer;
    return this;
  }

  /**
   * Get unitCountInactivityTimer
   * @return unitCountInactivityTimer
   **/
  @JsonProperty(value = "unitCountInactivityTimer")
  @ApiModelProperty(value = "")
  
  public Integer getUnitCountInactivityTimer() {
    return unitCountInactivityTimer;
  }

  public void setUnitCountInactivityTimer(Integer unitCountInactivityTimer) {
    this.unitCountInactivityTimer = unitCountInactivityTimer;
  }

  public PDUSessionChargingInformation rANSecondaryRATUsageReport(RANSecondaryRATUsageReport rANSecondaryRATUsageReport) {
    this.rANSecondaryRATUsageReport = rANSecondaryRATUsageReport;
    return this;
  }

  /**
   * Get rANSecondaryRATUsageReport
   * @return rANSecondaryRATUsageReport
   **/
  @JsonProperty(value = "rANSecondaryRATUsageReport")
  @ApiModelProperty(value = "")
  @Valid 
  public RANSecondaryRATUsageReport getrANSecondaryRATUsageReport() {
    return rANSecondaryRATUsageReport;
  }

  public void setrANSecondaryRATUsageReport(RANSecondaryRATUsageReport rANSecondaryRATUsageReport) {
    this.rANSecondaryRATUsageReport = rANSecondaryRATUsageReport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDUSessionChargingInformation pdUSessionChargingInformation = (PDUSessionChargingInformation) o;
    return Objects.equals(this.chargingId, pdUSessionChargingInformation.chargingId) &&
        Objects.equals(this.homeProvidedChargingId, pdUSessionChargingInformation.homeProvidedChargingId) &&
        Objects.equals(this.userInformation, pdUSessionChargingInformation.userInformation) &&
        Objects.equals(this.userLocationinfo, pdUSessionChargingInformation.userLocationinfo) &&
        Objects.equals(this.mAPDUNon3GPPUserLocationInfo, pdUSessionChargingInformation.mAPDUNon3GPPUserLocationInfo) &&
        Objects.equals(this.non3GPPUserLocationTime, pdUSessionChargingInformation.non3GPPUserLocationTime) &&
        Objects.equals(this.mAPDUNon3GPPUserLocationTime, pdUSessionChargingInformation.mAPDUNon3GPPUserLocationTime) &&
        Objects.equals(this.presenceReportingAreaInformation, pdUSessionChargingInformation.presenceReportingAreaInformation) &&
        Objects.equals(this.uetimeZone, pdUSessionChargingInformation.uetimeZone) &&
        Objects.equals(this.pduSessionInformation, pdUSessionChargingInformation.pduSessionInformation) &&
        Objects.equals(this.unitCountInactivityTimer, pdUSessionChargingInformation.unitCountInactivityTimer) &&
        Objects.equals(this.rANSecondaryRATUsageReport, pdUSessionChargingInformation.rANSecondaryRATUsageReport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargingId, homeProvidedChargingId, userInformation, userLocationinfo, mAPDUNon3GPPUserLocationInfo, non3GPPUserLocationTime, mAPDUNon3GPPUserLocationTime, presenceReportingAreaInformation, uetimeZone, pduSessionInformation, unitCountInactivityTimer, rANSecondaryRATUsageReport);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDUSessionChargingInformation {\n");
    
    sb.append("    chargingId: ").append(toIndentedString(chargingId)).append("\n");
    sb.append("    homeProvidedChargingId: ").append(toIndentedString(homeProvidedChargingId)).append("\n");
    sb.append("    userInformation: ").append(toIndentedString(userInformation)).append("\n");
    sb.append("    userLocationinfo: ").append(toIndentedString(userLocationinfo)).append("\n");
    sb.append("    mAPDUNon3GPPUserLocationInfo: ").append(toIndentedString(mAPDUNon3GPPUserLocationInfo)).append("\n");
    sb.append("    non3GPPUserLocationTime: ").append(toIndentedString(non3GPPUserLocationTime)).append("\n");
    sb.append("    mAPDUNon3GPPUserLocationTime: ").append(toIndentedString(mAPDUNon3GPPUserLocationTime)).append("\n");
    sb.append("    presenceReportingAreaInformation: ").append(toIndentedString(presenceReportingAreaInformation)).append("\n");
    sb.append("    uetimeZone: ").append(toIndentedString(uetimeZone)).append("\n");
    sb.append("    pduSessionInformation: ").append(toIndentedString(pduSessionInformation)).append("\n");
    sb.append("    unitCountInactivityTimer: ").append(toIndentedString(unitCountInactivityTimer)).append("\n");
    sb.append("    rANSecondaryRATUsageReport: ").append(toIndentedString(rANSecondaryRATUsageReport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

