/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * QosCharacteristics
 */
@JsonPropertyOrder({
  QosCharacteristics.JSON_PROPERTY_5QI,
  QosCharacteristics.JSON_PROPERTY_RESOURCE_TYPE,
  QosCharacteristics.JSON_PROPERTY_PRIORITY_LEVEL,
  QosCharacteristics.JSON_PROPERTY_PACKET_DELAY_BUDGET,
  QosCharacteristics.JSON_PROPERTY_PACKET_ERROR_RATE,
  QosCharacteristics.JSON_PROPERTY_AVERAGING_WINDOW,
  QosCharacteristics.JSON_PROPERTY_MAX_DATA_BURST_VOL,
  QosCharacteristics.JSON_PROPERTY_EXT_MAX_DATA_BURST_VOL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class QosCharacteristics   {
  public static final String JSON_PROPERTY_5QI = "5qi";
  @JsonProperty(JSON_PROPERTY_5QI)
  private Integer _5qi;

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  private QosResourceType resourceType;

  public static final String JSON_PROPERTY_PRIORITY_LEVEL = "priorityLevel";
  @JsonProperty(JSON_PROPERTY_PRIORITY_LEVEL)
  private Integer priorityLevel;

  public static final String JSON_PROPERTY_PACKET_DELAY_BUDGET = "packetDelayBudget";
  @JsonProperty(JSON_PROPERTY_PACKET_DELAY_BUDGET)
  private Integer packetDelayBudget;

  public static final String JSON_PROPERTY_PACKET_ERROR_RATE = "packetErrorRate";
  @JsonProperty(JSON_PROPERTY_PACKET_ERROR_RATE)
  private String packetErrorRate;

  public static final String JSON_PROPERTY_AVERAGING_WINDOW = "averagingWindow";
  @JsonProperty(JSON_PROPERTY_AVERAGING_WINDOW)
  private Integer averagingWindow = 2000;

  public static final String JSON_PROPERTY_MAX_DATA_BURST_VOL = "maxDataBurstVol";
  @JsonProperty(JSON_PROPERTY_MAX_DATA_BURST_VOL)
  private Integer maxDataBurstVol;

  public static final String JSON_PROPERTY_EXT_MAX_DATA_BURST_VOL = "extMaxDataBurstVol";
  @JsonProperty(JSON_PROPERTY_EXT_MAX_DATA_BURST_VOL)
  private Integer extMaxDataBurstVol;

  public QosCharacteristics _5qi(Integer _5qi) {
    this._5qi = _5qi;
    return this;
  }

  /**
   * Get _5qi
   * minimum: 0
   * maximum: 255
   * @return _5qi
   **/
  @JsonProperty(value = "5qi")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(0) @Max(255)
  public Integer get5qi() {
    return _5qi;
  }

  public void set5qi(Integer _5qi) {
    this._5qi = _5qi;
  }

  public QosCharacteristics resourceType(QosResourceType resourceType) {
    this.resourceType = resourceType;
    return this;
  }

  /**
   * Get resourceType
   * @return resourceType
   **/
  @JsonProperty(value = "resourceType")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public QosResourceType getResourceType() {
    return resourceType;
  }

  public void setResourceType(QosResourceType resourceType) {
    this.resourceType = resourceType;
  }

  public QosCharacteristics priorityLevel(Integer priorityLevel) {
    this.priorityLevel = priorityLevel;
    return this;
  }

  /**
   * Get priorityLevel
   * minimum: 1
   * maximum: 127
   * @return priorityLevel
   **/
  @JsonProperty(value = "priorityLevel")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(1) @Max(127)
  public Integer getPriorityLevel() {
    return priorityLevel;
  }

  public void setPriorityLevel(Integer priorityLevel) {
    this.priorityLevel = priorityLevel;
  }

  public QosCharacteristics packetDelayBudget(Integer packetDelayBudget) {
    this.packetDelayBudget = packetDelayBudget;
    return this;
  }

  /**
   * Get packetDelayBudget
   * minimum: 1
   * @return packetDelayBudget
   **/
  @JsonProperty(value = "packetDelayBudget")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Min(1)
  public Integer getPacketDelayBudget() {
    return packetDelayBudget;
  }

  public void setPacketDelayBudget(Integer packetDelayBudget) {
    this.packetDelayBudget = packetDelayBudget;
  }

  public QosCharacteristics packetErrorRate(String packetErrorRate) {
    this.packetErrorRate = packetErrorRate;
    return this;
  }

  /**
   * Get packetErrorRate
   * @return packetErrorRate
   **/
  @JsonProperty(value = "packetErrorRate")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Pattern(regexp="^([0-9]E-[0-9])$")
  public String getPacketErrorRate() {
    return packetErrorRate;
  }

  public void setPacketErrorRate(String packetErrorRate) {
    this.packetErrorRate = packetErrorRate;
  }

  public QosCharacteristics averagingWindow(Integer averagingWindow) {
    this.averagingWindow = averagingWindow;
    return this;
  }

  /**
   * Get averagingWindow
   * minimum: 1
   * maximum: 4095
   * @return averagingWindow
   **/
  @JsonProperty(value = "averagingWindow")
  @ApiModelProperty(value = "")
   @Min(1) @Max(4095)
  public Integer getAveragingWindow() {
    return averagingWindow;
  }

  public void setAveragingWindow(Integer averagingWindow) {
    this.averagingWindow = averagingWindow;
  }

  public QosCharacteristics maxDataBurstVol(Integer maxDataBurstVol) {
    this.maxDataBurstVol = maxDataBurstVol;
    return this;
  }

  /**
   * Get maxDataBurstVol
   * minimum: 1
   * maximum: 4095
   * @return maxDataBurstVol
   **/
  @JsonProperty(value = "maxDataBurstVol")
  @ApiModelProperty(value = "")
   @Min(1) @Max(4095)
  public Integer getMaxDataBurstVol() {
    return maxDataBurstVol;
  }

  public void setMaxDataBurstVol(Integer maxDataBurstVol) {
    this.maxDataBurstVol = maxDataBurstVol;
  }

  public QosCharacteristics extMaxDataBurstVol(Integer extMaxDataBurstVol) {
    this.extMaxDataBurstVol = extMaxDataBurstVol;
    return this;
  }

  /**
   * Get extMaxDataBurstVol
   * minimum: 4096
   * maximum: 2000000
   * @return extMaxDataBurstVol
   **/
  @JsonProperty(value = "extMaxDataBurstVol")
  @ApiModelProperty(value = "")
   @Min(4096) @Max(2000000)
  public Integer getExtMaxDataBurstVol() {
    return extMaxDataBurstVol;
  }

  public void setExtMaxDataBurstVol(Integer extMaxDataBurstVol) {
    this.extMaxDataBurstVol = extMaxDataBurstVol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QosCharacteristics qosCharacteristics = (QosCharacteristics) o;
    return Objects.equals(this._5qi, qosCharacteristics._5qi) &&
        Objects.equals(this.resourceType, qosCharacteristics.resourceType) &&
        Objects.equals(this.priorityLevel, qosCharacteristics.priorityLevel) &&
        Objects.equals(this.packetDelayBudget, qosCharacteristics.packetDelayBudget) &&
        Objects.equals(this.packetErrorRate, qosCharacteristics.packetErrorRate) &&
        Objects.equals(this.averagingWindow, qosCharacteristics.averagingWindow) &&
        Objects.equals(this.maxDataBurstVol, qosCharacteristics.maxDataBurstVol) &&
        Objects.equals(this.extMaxDataBurstVol, qosCharacteristics.extMaxDataBurstVol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_5qi, resourceType, priorityLevel, packetDelayBudget, packetErrorRate, averagingWindow, maxDataBurstVol, extMaxDataBurstVol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QosCharacteristics {\n");
    
    sb.append("    _5qi: ").append(toIndentedString(_5qi)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    priorityLevel: ").append(toIndentedString(priorityLevel)).append("\n");
    sb.append("    packetDelayBudget: ").append(toIndentedString(packetDelayBudget)).append("\n");
    sb.append("    packetErrorRate: ").append(toIndentedString(packetErrorRate)).append("\n");
    sb.append("    averagingWindow: ").append(toIndentedString(averagingWindow)).append("\n");
    sb.append("    maxDataBurstVol: ").append(toIndentedString(maxDataBurstVol)).append("\n");
    sb.append("    extMaxDataBurstVol: ").append(toIndentedString(extMaxDataBurstVol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

