/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RanNasRelCause
 */
@JsonPropertyOrder({
  RanNasRelCause.JSON_PROPERTY_NG_AP_CAUSE,
  RanNasRelCause.JSON_PROPERTY_5G_MM_CAUSE,
  RanNasRelCause.JSON_PROPERTY_5G_SM_CAUSE,
  RanNasRelCause.JSON_PROPERTY_EPS_CAUSE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RanNasRelCause   {
  public static final String JSON_PROPERTY_NG_AP_CAUSE = "ngApCause";
  @JsonProperty(JSON_PROPERTY_NG_AP_CAUSE)
  private NgApCause ngApCause;

  public static final String JSON_PROPERTY_5G_MM_CAUSE = "5gMmCause";
  @JsonProperty(JSON_PROPERTY_5G_MM_CAUSE)
  private Integer _5gMmCause;

  public static final String JSON_PROPERTY_5G_SM_CAUSE = "5gSmCause";
  @JsonProperty(JSON_PROPERTY_5G_SM_CAUSE)
  private Integer _5gSmCause;

  public static final String JSON_PROPERTY_EPS_CAUSE = "epsCause";
  @JsonProperty(JSON_PROPERTY_EPS_CAUSE)
  private String epsCause;

  public RanNasRelCause ngApCause(NgApCause ngApCause) {
    this.ngApCause = ngApCause;
    return this;
  }

  /**
   * Get ngApCause
   * @return ngApCause
   **/
  @JsonProperty(value = "ngApCause")
  @ApiModelProperty(value = "")
  @Valid 
  public NgApCause getNgApCause() {
    return ngApCause;
  }

  public void setNgApCause(NgApCause ngApCause) {
    this.ngApCause = ngApCause;
  }

  public RanNasRelCause _5gMmCause(Integer _5gMmCause) {
    this._5gMmCause = _5gMmCause;
    return this;
  }

  /**
   * Get _5gMmCause
   * minimum: 0
   * @return _5gMmCause
   **/
  @JsonProperty(value = "5gMmCause")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer get5gMmCause() {
    return _5gMmCause;
  }

  public void set5gMmCause(Integer _5gMmCause) {
    this._5gMmCause = _5gMmCause;
  }

  public RanNasRelCause _5gSmCause(Integer _5gSmCause) {
    this._5gSmCause = _5gSmCause;
    return this;
  }

  /**
   * Get _5gSmCause
   * minimum: 0
   * @return _5gSmCause
   **/
  @JsonProperty(value = "5gSmCause")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer get5gSmCause() {
    return _5gSmCause;
  }

  public void set5gSmCause(Integer _5gSmCause) {
    this._5gSmCause = _5gSmCause;
  }

  public RanNasRelCause epsCause(String epsCause) {
    this.epsCause = epsCause;
    return this;
  }

  /**
   * Defines the EPS RAN/NAS release cause.
   * @return epsCause
   **/
  @JsonProperty(value = "epsCause")
  @ApiModelProperty(value = "Defines the EPS RAN/NAS release cause.")
  
  public String getEpsCause() {
    return epsCause;
  }

  public void setEpsCause(String epsCause) {
    this.epsCause = epsCause;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RanNasRelCause ranNasRelCause = (RanNasRelCause) o;
    return Objects.equals(this.ngApCause, ranNasRelCause.ngApCause) &&
        Objects.equals(this._5gMmCause, ranNasRelCause._5gMmCause) &&
        Objects.equals(this._5gSmCause, ranNasRelCause._5gSmCause) &&
        Objects.equals(this.epsCause, ranNasRelCause.epsCause);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ngApCause, _5gMmCause, _5gSmCause, epsCause);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RanNasRelCause {\n");
    
    sb.append("    ngApCause: ").append(toIndentedString(ngApCause)).append("\n");
    sb.append("    _5gMmCause: ").append(toIndentedString(_5gMmCause)).append("\n");
    sb.append("    _5gSmCause: ").append(toIndentedString(_5gSmCause)).append("\n");
    sb.append("    epsCause: ").append(toIndentedString(epsCause)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

