/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RecipientAddress
 */
@JsonPropertyOrder({
  RecipientAddress.JSON_PROPERTY_RECIPIENT_ADDRESS_INFO,
  RecipientAddress.JSON_PROPERTY_S_MADDRESSEE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RecipientAddress   {
  public static final String JSON_PROPERTY_RECIPIENT_ADDRESS_INFO = "recipientAddressInfo";
  @JsonProperty(JSON_PROPERTY_RECIPIENT_ADDRESS_INFO)
  private SMAddressInfo recipientAddressInfo;

  public static final String JSON_PROPERTY_S_MADDRESSEE_TYPE = "sMaddresseeType";
  @JsonProperty(JSON_PROPERTY_S_MADDRESSEE_TYPE)
  private SMAddresseeType sMaddresseeType;

  public RecipientAddress recipientAddressInfo(SMAddressInfo recipientAddressInfo) {
    this.recipientAddressInfo = recipientAddressInfo;
    return this;
  }

  /**
   * Get recipientAddressInfo
   * @return recipientAddressInfo
   **/
  @JsonProperty(value = "recipientAddressInfo")
  @ApiModelProperty(value = "")
  @Valid 
  public SMAddressInfo getRecipientAddressInfo() {
    return recipientAddressInfo;
  }

  public void setRecipientAddressInfo(SMAddressInfo recipientAddressInfo) {
    this.recipientAddressInfo = recipientAddressInfo;
  }

  public RecipientAddress sMaddresseeType(SMAddresseeType sMaddresseeType) {
    this.sMaddresseeType = sMaddresseeType;
    return this;
  }

  /**
   * Get sMaddresseeType
   * @return sMaddresseeType
   **/
  @JsonProperty(value = "sMaddresseeType")
  @ApiModelProperty(value = "")
  
  public SMAddresseeType getsMaddresseeType() {
    return sMaddresseeType;
  }

  public void setsMaddresseeType(SMAddresseeType sMaddresseeType) {
    this.sMaddresseeType = sMaddresseeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientAddress recipientAddress = (RecipientAddress) o;
    return Objects.equals(this.recipientAddressInfo, recipientAddress.recipientAddressInfo) &&
        Objects.equals(this.sMaddresseeType, recipientAddress.sMaddresseeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientAddressInfo, sMaddresseeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientAddress {\n");
    
    sb.append("    recipientAddressInfo: ").append(toIndentedString(recipientAddressInfo)).append("\n");
    sb.append("    sMaddresseeType: ").append(toIndentedString(sMaddresseeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

