/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RedirectServer
 */
@JsonPropertyOrder({
  RedirectServer.JSON_PROPERTY_REDIRECT_ADDRESS_TYPE,
  RedirectServer.JSON_PROPERTY_REDIRECT_SERVER_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RedirectServer   {
  public static final String JSON_PROPERTY_REDIRECT_ADDRESS_TYPE = "redirectAddressType";
  @JsonProperty(JSON_PROPERTY_REDIRECT_ADDRESS_TYPE)
  private RedirectAddressType redirectAddressType;

  public static final String JSON_PROPERTY_REDIRECT_SERVER_ADDRESS = "redirectServerAddress";
  @JsonProperty(JSON_PROPERTY_REDIRECT_SERVER_ADDRESS)
  private String redirectServerAddress;

  public RedirectServer redirectAddressType(RedirectAddressType redirectAddressType) {
    this.redirectAddressType = redirectAddressType;
    return this;
  }

  /**
   * Get redirectAddressType
   * @return redirectAddressType
   **/
  @JsonProperty(value = "redirectAddressType")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public RedirectAddressType getRedirectAddressType() {
    return redirectAddressType;
  }

  public void setRedirectAddressType(RedirectAddressType redirectAddressType) {
    this.redirectAddressType = redirectAddressType;
  }

  public RedirectServer redirectServerAddress(String redirectServerAddress) {
    this.redirectServerAddress = redirectServerAddress;
    return this;
  }

  /**
   * Get redirectServerAddress
   * @return redirectServerAddress
   **/
  @JsonProperty(value = "redirectServerAddress")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getRedirectServerAddress() {
    return redirectServerAddress;
  }

  public void setRedirectServerAddress(String redirectServerAddress) {
    this.redirectServerAddress = redirectServerAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedirectServer redirectServer = (RedirectServer) o;
    return Objects.equals(this.redirectAddressType, redirectServer.redirectAddressType) &&
        Objects.equals(this.redirectServerAddress, redirectServer.redirectServerAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirectAddressType, redirectServerAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedirectServer {\n");
    
    sb.append("    redirectAddressType: ").append(toIndentedString(redirectAddressType)).append("\n");
    sb.append("    redirectServerAddress: ").append(toIndentedString(redirectServerAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

