/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RegistrationChargingInformation
 */
@JsonPropertyOrder({
  RegistrationChargingInformation.JSON_PROPERTY_REGISTRATION_MESSAGETYPE,
  RegistrationChargingInformation.JSON_PROPERTY_USER_INFORMATION,
  RegistrationChargingInformation.JSON_PROPERTY_USER_LOCATIONINFO,
  RegistrationChargingInformation.JSON_PROPERTY_P_S_CELL_INFORMATION,
  RegistrationChargingInformation.JSON_PROPERTY_UETIME_ZONE,
  RegistrationChargingInformation.JSON_PROPERTY_R_A_T_TYPE,
  RegistrationChargingInformation.JSON_PROPERTY_5G_M_M_CAPABILITY,
  RegistrationChargingInformation.JSON_PROPERTY_M_I_C_O_MODE_INDICATION,
  RegistrationChargingInformation.JSON_PROPERTY_SMS_INDICATION,
  RegistrationChargingInformation.JSON_PROPERTY_TAI_LIST,
  RegistrationChargingInformation.JSON_PROPERTY_SERVICE_AREA_RESTRICTION,
  RegistrationChargingInformation.JSON_PROPERTY_REQUESTED_N_S_S_A_I,
  RegistrationChargingInformation.JSON_PROPERTY_ALLOWED_N_S_S_A_I,
  RegistrationChargingInformation.JSON_PROPERTY_REJECTED_N_S_S_A_I,
  RegistrationChargingInformation.JSON_PROPERTY_N_S_S_A_I_MAP_LIST,
  RegistrationChargingInformation.JSON_PROPERTY_AMF_UE_NGAP_ID,
  RegistrationChargingInformation.JSON_PROPERTY_RAN_UE_NGAP_ID,
  RegistrationChargingInformation.JSON_PROPERTY_RAN_NODE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RegistrationChargingInformation   {
  public static final String JSON_PROPERTY_REGISTRATION_MESSAGETYPE = "registrationMessagetype";
  @JsonProperty(JSON_PROPERTY_REGISTRATION_MESSAGETYPE)
  private RegistrationMessageType registrationMessagetype;

  public static final String JSON_PROPERTY_USER_INFORMATION = "userInformation";
  @JsonProperty(JSON_PROPERTY_USER_INFORMATION)
  private UserInformation userInformation;

  public static final String JSON_PROPERTY_USER_LOCATIONINFO = "userLocationinfo";
  @JsonProperty(JSON_PROPERTY_USER_LOCATIONINFO)
  private UserLocation userLocationinfo;

  public static final String JSON_PROPERTY_P_S_CELL_INFORMATION = "pSCellInformation";
  @JsonProperty(JSON_PROPERTY_P_S_CELL_INFORMATION)
  private PSCellInformation pSCellInformation;

  public static final String JSON_PROPERTY_UETIME_ZONE = "uetimeZone";
  @JsonProperty(JSON_PROPERTY_UETIME_ZONE)
  private String uetimeZone;

  public static final String JSON_PROPERTY_R_A_T_TYPE = "rATType";
  @JsonProperty(JSON_PROPERTY_R_A_T_TYPE)
  private RatType rATType;

  public static final String JSON_PROPERTY_5G_M_M_CAPABILITY = "5GMMCapability";
  @JsonProperty(JSON_PROPERTY_5G_M_M_CAPABILITY)
  private byte[] _5gMMCapability;

  public static final String JSON_PROPERTY_M_I_C_O_MODE_INDICATION = "mICOModeIndication";
  @JsonProperty(JSON_PROPERTY_M_I_C_O_MODE_INDICATION)
  private MICOModeIndication mICOModeIndication;

  public static final String JSON_PROPERTY_SMS_INDICATION = "smsIndication";
  @JsonProperty(JSON_PROPERTY_SMS_INDICATION)
  private SmsIndication smsIndication;

  public static final String JSON_PROPERTY_TAI_LIST = "taiList";
  @JsonProperty(JSON_PROPERTY_TAI_LIST)
  private List<@Valid Tai> taiList;

  public static final String JSON_PROPERTY_SERVICE_AREA_RESTRICTION = "serviceAreaRestriction";
  @JsonProperty(JSON_PROPERTY_SERVICE_AREA_RESTRICTION)
  private List<@Valid ServiceAreaRestriction> serviceAreaRestriction;

  public static final String JSON_PROPERTY_REQUESTED_N_S_S_A_I = "requestedNSSAI";
  @JsonProperty(JSON_PROPERTY_REQUESTED_N_S_S_A_I)
  private List<@Valid Snssai> requestedNSSAI;

  public static final String JSON_PROPERTY_ALLOWED_N_S_S_A_I = "allowedNSSAI";
  @JsonProperty(JSON_PROPERTY_ALLOWED_N_S_S_A_I)
  private List<@Valid Snssai> allowedNSSAI;

  public static final String JSON_PROPERTY_REJECTED_N_S_S_A_I = "rejectedNSSAI";
  @JsonProperty(JSON_PROPERTY_REJECTED_N_S_S_A_I)
  private List<@Valid Snssai> rejectedNSSAI;

  public static final String JSON_PROPERTY_N_S_S_A_I_MAP_LIST = "nSSAIMapList";
  @JsonProperty(JSON_PROPERTY_N_S_S_A_I_MAP_LIST)
  private List<@Valid NSSAIMap> nSSAIMapList;

  public static final String JSON_PROPERTY_AMF_UE_NGAP_ID = "amfUeNgapId";
  @JsonProperty(JSON_PROPERTY_AMF_UE_NGAP_ID)
  private Integer amfUeNgapId;

  public static final String JSON_PROPERTY_RAN_UE_NGAP_ID = "ranUeNgapId";
  @JsonProperty(JSON_PROPERTY_RAN_UE_NGAP_ID)
  private Integer ranUeNgapId;

  public static final String JSON_PROPERTY_RAN_NODE_ID = "ranNodeId";
  @JsonProperty(JSON_PROPERTY_RAN_NODE_ID)
  private GlobalRanNodeId ranNodeId;

  public RegistrationChargingInformation registrationMessagetype(RegistrationMessageType registrationMessagetype) {
    this.registrationMessagetype = registrationMessagetype;
    return this;
  }

  /**
   * Get registrationMessagetype
   * @return registrationMessagetype
   **/
  @JsonProperty(value = "registrationMessagetype")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public RegistrationMessageType getRegistrationMessagetype() {
    return registrationMessagetype;
  }

  public void setRegistrationMessagetype(RegistrationMessageType registrationMessagetype) {
    this.registrationMessagetype = registrationMessagetype;
  }

  public RegistrationChargingInformation userInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
    return this;
  }

  /**
   * Get userInformation
   * @return userInformation
   **/
  @JsonProperty(value = "userInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public UserInformation getUserInformation() {
    return userInformation;
  }

  public void setUserInformation(UserInformation userInformation) {
    this.userInformation = userInformation;
  }

  public RegistrationChargingInformation userLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
    return this;
  }

  /**
   * Get userLocationinfo
   * @return userLocationinfo
   **/
  @JsonProperty(value = "userLocationinfo")
  @ApiModelProperty(value = "")
  @Valid 
  public UserLocation getUserLocationinfo() {
    return userLocationinfo;
  }

  public void setUserLocationinfo(UserLocation userLocationinfo) {
    this.userLocationinfo = userLocationinfo;
  }

  public RegistrationChargingInformation pSCellInformation(PSCellInformation pSCellInformation) {
    this.pSCellInformation = pSCellInformation;
    return this;
  }

  /**
   * Get pSCellInformation
   * @return pSCellInformation
   **/
  @JsonProperty(value = "pSCellInformation")
  @ApiModelProperty(value = "")
  @Valid 
  public PSCellInformation getpSCellInformation() {
    return pSCellInformation;
  }

  public void setpSCellInformation(PSCellInformation pSCellInformation) {
    this.pSCellInformation = pSCellInformation;
  }

  public RegistrationChargingInformation uetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
    return this;
  }

  /**
   * Get uetimeZone
   * @return uetimeZone
   **/
  @JsonProperty(value = "uetimeZone")
  @ApiModelProperty(value = "")
  
  public String getUetimeZone() {
    return uetimeZone;
  }

  public void setUetimeZone(String uetimeZone) {
    this.uetimeZone = uetimeZone;
  }

  public RegistrationChargingInformation rATType(RatType rATType) {
    this.rATType = rATType;
    return this;
  }

  /**
   * Get rATType
   * @return rATType
   **/
  @JsonProperty(value = "rATType")
  @ApiModelProperty(value = "")
  
  public RatType getrATType() {
    return rATType;
  }

  public void setrATType(RatType rATType) {
    this.rATType = rATType;
  }

  public RegistrationChargingInformation _5gMMCapability(byte[] _5gMMCapability) {
    this._5gMMCapability = _5gMMCapability;
    return this;
  }

  /**
   * Get _5gMMCapability
   * @return _5gMMCapability
   **/
  @JsonProperty(value = "5GMMCapability")
  @ApiModelProperty(value = "")
  
  public byte[] get5gMMCapability() {
    return _5gMMCapability;
  }

  public void set5gMMCapability(byte[] _5gMMCapability) {
    this._5gMMCapability = _5gMMCapability;
  }

  public RegistrationChargingInformation mICOModeIndication(MICOModeIndication mICOModeIndication) {
    this.mICOModeIndication = mICOModeIndication;
    return this;
  }

  /**
   * Get mICOModeIndication
   * @return mICOModeIndication
   **/
  @JsonProperty(value = "mICOModeIndication")
  @ApiModelProperty(value = "")
  
  public MICOModeIndication getmICOModeIndication() {
    return mICOModeIndication;
  }

  public void setmICOModeIndication(MICOModeIndication mICOModeIndication) {
    this.mICOModeIndication = mICOModeIndication;
  }

  public RegistrationChargingInformation smsIndication(SmsIndication smsIndication) {
    this.smsIndication = smsIndication;
    return this;
  }

  /**
   * Get smsIndication
   * @return smsIndication
   **/
  @JsonProperty(value = "smsIndication")
  @ApiModelProperty(value = "")
  
  public SmsIndication getSmsIndication() {
    return smsIndication;
  }

  public void setSmsIndication(SmsIndication smsIndication) {
    this.smsIndication = smsIndication;
  }

  public RegistrationChargingInformation taiList(List<@Valid Tai> taiList) {
    this.taiList = taiList;
    return this;
  }

  public RegistrationChargingInformation addTaiListItem(Tai taiListItem) {
    if (this.taiList == null) {
      this.taiList = new ArrayList<>();
    }
    this.taiList.add(taiListItem);
    return this;
  }

  /**
   * Get taiList
   * @return taiList
   **/
  @JsonProperty(value = "taiList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Tai> getTaiList() {
    return taiList;
  }

  public void setTaiList(List<@Valid Tai> taiList) {
    this.taiList = taiList;
  }

  public RegistrationChargingInformation serviceAreaRestriction(List<@Valid ServiceAreaRestriction> serviceAreaRestriction) {
    this.serviceAreaRestriction = serviceAreaRestriction;
    return this;
  }

  public RegistrationChargingInformation addServiceAreaRestrictionItem(ServiceAreaRestriction serviceAreaRestrictionItem) {
    if (this.serviceAreaRestriction == null) {
      this.serviceAreaRestriction = new ArrayList<>();
    }
    this.serviceAreaRestriction.add(serviceAreaRestrictionItem);
    return this;
  }

  /**
   * Get serviceAreaRestriction
   * @return serviceAreaRestriction
   **/
  @JsonProperty(value = "serviceAreaRestriction")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid ServiceAreaRestriction> getServiceAreaRestriction() {
    return serviceAreaRestriction;
  }

  public void setServiceAreaRestriction(List<@Valid ServiceAreaRestriction> serviceAreaRestriction) {
    this.serviceAreaRestriction = serviceAreaRestriction;
  }

  public RegistrationChargingInformation requestedNSSAI(List<@Valid Snssai> requestedNSSAI) {
    this.requestedNSSAI = requestedNSSAI;
    return this;
  }

  public RegistrationChargingInformation addRequestedNSSAIItem(Snssai requestedNSSAIItem) {
    if (this.requestedNSSAI == null) {
      this.requestedNSSAI = new ArrayList<>();
    }
    this.requestedNSSAI.add(requestedNSSAIItem);
    return this;
  }

  /**
   * Get requestedNSSAI
   * @return requestedNSSAI
   **/
  @JsonProperty(value = "requestedNSSAI")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Snssai> getRequestedNSSAI() {
    return requestedNSSAI;
  }

  public void setRequestedNSSAI(List<@Valid Snssai> requestedNSSAI) {
    this.requestedNSSAI = requestedNSSAI;
  }

  public RegistrationChargingInformation allowedNSSAI(List<@Valid Snssai> allowedNSSAI) {
    this.allowedNSSAI = allowedNSSAI;
    return this;
  }

  public RegistrationChargingInformation addAllowedNSSAIItem(Snssai allowedNSSAIItem) {
    if (this.allowedNSSAI == null) {
      this.allowedNSSAI = new ArrayList<>();
    }
    this.allowedNSSAI.add(allowedNSSAIItem);
    return this;
  }

  /**
   * Get allowedNSSAI
   * @return allowedNSSAI
   **/
  @JsonProperty(value = "allowedNSSAI")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Snssai> getAllowedNSSAI() {
    return allowedNSSAI;
  }

  public void setAllowedNSSAI(List<@Valid Snssai> allowedNSSAI) {
    this.allowedNSSAI = allowedNSSAI;
  }

  public RegistrationChargingInformation rejectedNSSAI(List<@Valid Snssai> rejectedNSSAI) {
    this.rejectedNSSAI = rejectedNSSAI;
    return this;
  }

  public RegistrationChargingInformation addRejectedNSSAIItem(Snssai rejectedNSSAIItem) {
    if (this.rejectedNSSAI == null) {
      this.rejectedNSSAI = new ArrayList<>();
    }
    this.rejectedNSSAI.add(rejectedNSSAIItem);
    return this;
  }

  /**
   * Get rejectedNSSAI
   * @return rejectedNSSAI
   **/
  @JsonProperty(value = "rejectedNSSAI")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid Snssai> getRejectedNSSAI() {
    return rejectedNSSAI;
  }

  public void setRejectedNSSAI(List<@Valid Snssai> rejectedNSSAI) {
    this.rejectedNSSAI = rejectedNSSAI;
  }

  public RegistrationChargingInformation nSSAIMapList(List<@Valid NSSAIMap> nSSAIMapList) {
    this.nSSAIMapList = nSSAIMapList;
    return this;
  }

  public RegistrationChargingInformation addNSSAIMapListItem(NSSAIMap nSSAIMapListItem) {
    if (this.nSSAIMapList == null) {
      this.nSSAIMapList = new ArrayList<>();
    }
    this.nSSAIMapList.add(nSSAIMapListItem);
    return this;
  }

  /**
   * Get nSSAIMapList
   * @return nSSAIMapList
   **/
  @JsonProperty(value = "nSSAIMapList")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid NSSAIMap> getnSSAIMapList() {
    return nSSAIMapList;
  }

  public void setnSSAIMapList(List<@Valid NSSAIMap> nSSAIMapList) {
    this.nSSAIMapList = nSSAIMapList;
  }

  public RegistrationChargingInformation amfUeNgapId(Integer amfUeNgapId) {
    this.amfUeNgapId = amfUeNgapId;
    return this;
  }

  /**
   * Get amfUeNgapId
   * @return amfUeNgapId
   **/
  @JsonProperty(value = "amfUeNgapId")
  @ApiModelProperty(value = "")
  
  public Integer getAmfUeNgapId() {
    return amfUeNgapId;
  }

  public void setAmfUeNgapId(Integer amfUeNgapId) {
    this.amfUeNgapId = amfUeNgapId;
  }

  public RegistrationChargingInformation ranUeNgapId(Integer ranUeNgapId) {
    this.ranUeNgapId = ranUeNgapId;
    return this;
  }

  /**
   * Get ranUeNgapId
   * @return ranUeNgapId
   **/
  @JsonProperty(value = "ranUeNgapId")
  @ApiModelProperty(value = "")
  
  public Integer getRanUeNgapId() {
    return ranUeNgapId;
  }

  public void setRanUeNgapId(Integer ranUeNgapId) {
    this.ranUeNgapId = ranUeNgapId;
  }

  public RegistrationChargingInformation ranNodeId(GlobalRanNodeId ranNodeId) {
    this.ranNodeId = ranNodeId;
    return this;
  }

  /**
   * Get ranNodeId
   * @return ranNodeId
   **/
  @JsonProperty(value = "ranNodeId")
  @ApiModelProperty(value = "")
  @Valid 
  public GlobalRanNodeId getRanNodeId() {
    return ranNodeId;
  }

  public void setRanNodeId(GlobalRanNodeId ranNodeId) {
    this.ranNodeId = ranNodeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistrationChargingInformation registrationChargingInformation = (RegistrationChargingInformation) o;
    return Objects.equals(this.registrationMessagetype, registrationChargingInformation.registrationMessagetype) &&
        Objects.equals(this.userInformation, registrationChargingInformation.userInformation) &&
        Objects.equals(this.userLocationinfo, registrationChargingInformation.userLocationinfo) &&
        Objects.equals(this.pSCellInformation, registrationChargingInformation.pSCellInformation) &&
        Objects.equals(this.uetimeZone, registrationChargingInformation.uetimeZone) &&
        Objects.equals(this.rATType, registrationChargingInformation.rATType) &&
        Objects.equals(this._5gMMCapability, registrationChargingInformation._5gMMCapability) &&
        Objects.equals(this.mICOModeIndication, registrationChargingInformation.mICOModeIndication) &&
        Objects.equals(this.smsIndication, registrationChargingInformation.smsIndication) &&
        Objects.equals(this.taiList, registrationChargingInformation.taiList) &&
        Objects.equals(this.serviceAreaRestriction, registrationChargingInformation.serviceAreaRestriction) &&
        Objects.equals(this.requestedNSSAI, registrationChargingInformation.requestedNSSAI) &&
        Objects.equals(this.allowedNSSAI, registrationChargingInformation.allowedNSSAI) &&
        Objects.equals(this.rejectedNSSAI, registrationChargingInformation.rejectedNSSAI) &&
        Objects.equals(this.nSSAIMapList, registrationChargingInformation.nSSAIMapList) &&
        Objects.equals(this.amfUeNgapId, registrationChargingInformation.amfUeNgapId) &&
        Objects.equals(this.ranUeNgapId, registrationChargingInformation.ranUeNgapId) &&
        Objects.equals(this.ranNodeId, registrationChargingInformation.ranNodeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registrationMessagetype, userInformation, userLocationinfo, pSCellInformation, uetimeZone, rATType, _5gMMCapability, mICOModeIndication, smsIndication, taiList, serviceAreaRestriction, requestedNSSAI, allowedNSSAI, rejectedNSSAI, nSSAIMapList, amfUeNgapId, ranUeNgapId, ranNodeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistrationChargingInformation {\n");
    
    sb.append("    registrationMessagetype: ").append(toIndentedString(registrationMessagetype)).append("\n");
    sb.append("    userInformation: ").append(toIndentedString(userInformation)).append("\n");
    sb.append("    userLocationinfo: ").append(toIndentedString(userLocationinfo)).append("\n");
    sb.append("    pSCellInformation: ").append(toIndentedString(pSCellInformation)).append("\n");
    sb.append("    uetimeZone: ").append(toIndentedString(uetimeZone)).append("\n");
    sb.append("    rATType: ").append(toIndentedString(rATType)).append("\n");
    sb.append("    _5gMMCapability: ").append(toIndentedString(_5gMMCapability)).append("\n");
    sb.append("    mICOModeIndication: ").append(toIndentedString(mICOModeIndication)).append("\n");
    sb.append("    smsIndication: ").append(toIndentedString(smsIndication)).append("\n");
    sb.append("    taiList: ").append(toIndentedString(taiList)).append("\n");
    sb.append("    serviceAreaRestriction: ").append(toIndentedString(serviceAreaRestriction)).append("\n");
    sb.append("    requestedNSSAI: ").append(toIndentedString(requestedNSSAI)).append("\n");
    sb.append("    allowedNSSAI: ").append(toIndentedString(allowedNSSAI)).append("\n");
    sb.append("    rejectedNSSAI: ").append(toIndentedString(rejectedNSSAI)).append("\n");
    sb.append("    nSSAIMapList: ").append(toIndentedString(nSSAIMapList)).append("\n");
    sb.append("    amfUeNgapId: ").append(toIndentedString(amfUeNgapId)).append("\n");
    sb.append("    ranUeNgapId: ").append(toIndentedString(ranUeNgapId)).append("\n");
    sb.append("    ranNodeId: ").append(toIndentedString(ranNodeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

