/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RoamingQBCInformation
 */
@JsonPropertyOrder({
  RoamingQBCInformation.JSON_PROPERTY_MULTIPLE_Q_F_ICONTAINER,
  RoamingQBCInformation.JSON_PROPERTY_U_P_F_I_D,
  RoamingQBCInformation.JSON_PROPERTY_ROAMING_CHARGING_PROFILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class RoamingQBCInformation   {
  public static final String JSON_PROPERTY_MULTIPLE_Q_F_ICONTAINER = "multipleQFIcontainer";
  @JsonProperty(JSON_PROPERTY_MULTIPLE_Q_F_ICONTAINER)
  private List<@Valid MultipleQFIcontainer> multipleQFIcontainer;

  public static final String JSON_PROPERTY_U_P_F_I_D = "uPFID";
  @JsonProperty(JSON_PROPERTY_U_P_F_I_D)
  private UUID uPFID;

  public static final String JSON_PROPERTY_ROAMING_CHARGING_PROFILE = "roamingChargingProfile";
  @JsonProperty(JSON_PROPERTY_ROAMING_CHARGING_PROFILE)
  private RoamingChargingProfile roamingChargingProfile;

  public RoamingQBCInformation multipleQFIcontainer(List<@Valid MultipleQFIcontainer> multipleQFIcontainer) {
    this.multipleQFIcontainer = multipleQFIcontainer;
    return this;
  }

  public RoamingQBCInformation addMultipleQFIcontainerItem(MultipleQFIcontainer multipleQFIcontainerItem) {
    if (this.multipleQFIcontainer == null) {
      this.multipleQFIcontainer = new ArrayList<>();
    }
    this.multipleQFIcontainer.add(multipleQFIcontainerItem);
    return this;
  }

  /**
   * Get multipleQFIcontainer
   * @return multipleQFIcontainer
   **/
  @JsonProperty(value = "multipleQFIcontainer")
  @ApiModelProperty(value = "")
  @Valid  @Size(min=0)
  public List<@Valid MultipleQFIcontainer> getMultipleQFIcontainer() {
    return multipleQFIcontainer;
  }

  public void setMultipleQFIcontainer(List<@Valid MultipleQFIcontainer> multipleQFIcontainer) {
    this.multipleQFIcontainer = multipleQFIcontainer;
  }

  public RoamingQBCInformation uPFID(UUID uPFID) {
    this.uPFID = uPFID;
    return this;
  }

  /**
   * Get uPFID
   * @return uPFID
   **/
  @JsonProperty(value = "uPFID")
  @ApiModelProperty(value = "")
  
  public UUID getuPFID() {
    return uPFID;
  }

  public void setuPFID(UUID uPFID) {
    this.uPFID = uPFID;
  }

  public RoamingQBCInformation roamingChargingProfile(RoamingChargingProfile roamingChargingProfile) {
    this.roamingChargingProfile = roamingChargingProfile;
    return this;
  }

  /**
   * Get roamingChargingProfile
   * @return roamingChargingProfile
   **/
  @JsonProperty(value = "roamingChargingProfile")
  @ApiModelProperty(value = "")
  @Valid 
  public RoamingChargingProfile getRoamingChargingProfile() {
    return roamingChargingProfile;
  }

  public void setRoamingChargingProfile(RoamingChargingProfile roamingChargingProfile) {
    this.roamingChargingProfile = roamingChargingProfile;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoamingQBCInformation roamingQBCInformation = (RoamingQBCInformation) o;
    return Objects.equals(this.multipleQFIcontainer, roamingQBCInformation.multipleQFIcontainer) &&
        Objects.equals(this.uPFID, roamingQBCInformation.uPFID) &&
        Objects.equals(this.roamingChargingProfile, roamingQBCInformation.roamingChargingProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(multipleQFIcontainer, uPFID, roamingChargingProfile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoamingQBCInformation {\n");
    
    sb.append("    multipleQFIcontainer: ").append(toIndentedString(multipleQFIcontainer)).append("\n");
    sb.append("    uPFID: ").append(toIndentedString(uPFID)).append("\n");
    sb.append("    roamingChargingProfile: ").append(toIndentedString(roamingChargingProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

