/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ServiceAreaId
 */
@JsonPropertyOrder({
  ServiceAreaId.JSON_PROPERTY_PLMN_ID,
  ServiceAreaId.JSON_PROPERTY_LAC,
  ServiceAreaId.JSON_PROPERTY_SAC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class ServiceAreaId   {
  public static final String JSON_PROPERTY_PLMN_ID = "plmnId";
  @JsonProperty(JSON_PROPERTY_PLMN_ID)
  private PlmnId plmnId;

  public static final String JSON_PROPERTY_LAC = "lac";
  @JsonProperty(JSON_PROPERTY_LAC)
  private String lac;

  public static final String JSON_PROPERTY_SAC = "sac";
  @JsonProperty(JSON_PROPERTY_SAC)
  private String sac;

  public ServiceAreaId plmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
    return this;
  }

  /**
   * Get plmnId
   * @return plmnId
   **/
  @JsonProperty(value = "plmnId")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public PlmnId getPlmnId() {
    return plmnId;
  }

  public void setPlmnId(PlmnId plmnId) {
    this.plmnId = plmnId;
  }

  public ServiceAreaId lac(String lac) {
    this.lac = lac;
    return this;
  }

  /**
   * Get lac
   * @return lac
   **/
  @JsonProperty(value = "lac")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Pattern(regexp="^[A-Fa-f0-9]{4}$")
  public String getLac() {
    return lac;
  }

  public void setLac(String lac) {
    this.lac = lac;
  }

  public ServiceAreaId sac(String sac) {
    this.sac = sac;
    return this;
  }

  /**
   * Get sac
   * @return sac
   **/
  @JsonProperty(value = "sac")
  @ApiModelProperty(required = true, value = "")
  @NotNull  @Pattern(regexp="^[A-Fa-f0-9]{4}$")
  public String getSac() {
    return sac;
  }

  public void setSac(String sac) {
    this.sac = sac;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAreaId serviceAreaId = (ServiceAreaId) o;
    return Objects.equals(this.plmnId, serviceAreaId.plmnId) &&
        Objects.equals(this.lac, serviceAreaId.lac) &&
        Objects.equals(this.sac, serviceAreaId.sac);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plmnId, lac, sac);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAreaId {\n");
    
    sb.append("    plmnId: ").append(toIndentedString(plmnId)).append("\n");
    sb.append("    lac: ").append(toIndentedString(lac)).append("\n");
    sb.append("    sac: ").append(toIndentedString(sac)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

