/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ServingNetworkFunctionID
 */
@JsonPropertyOrder({
  ServingNetworkFunctionID.JSON_PROPERTY_SERVING_NETWORK_FUNCTION_INFORMATION,
  ServingNetworkFunctionID.JSON_PROPERTY_A_M_F_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class ServingNetworkFunctionID   {
  public static final String JSON_PROPERTY_SERVING_NETWORK_FUNCTION_INFORMATION = "servingNetworkFunctionInformation";
  @JsonProperty(JSON_PROPERTY_SERVING_NETWORK_FUNCTION_INFORMATION)
  private NFIdentification servingNetworkFunctionInformation;

  public static final String JSON_PROPERTY_A_M_F_ID = "aMFId";
  @JsonProperty(JSON_PROPERTY_A_M_F_ID)
  private String aMFId;

  public ServingNetworkFunctionID servingNetworkFunctionInformation(NFIdentification servingNetworkFunctionInformation) {
    this.servingNetworkFunctionInformation = servingNetworkFunctionInformation;
    return this;
  }

  /**
   * Get servingNetworkFunctionInformation
   * @return servingNetworkFunctionInformation
   **/
  @JsonProperty(value = "servingNetworkFunctionInformation")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public NFIdentification getServingNetworkFunctionInformation() {
    return servingNetworkFunctionInformation;
  }

  public void setServingNetworkFunctionInformation(NFIdentification servingNetworkFunctionInformation) {
    this.servingNetworkFunctionInformation = servingNetworkFunctionInformation;
  }

  public ServingNetworkFunctionID aMFId(String aMFId) {
    this.aMFId = aMFId;
    return this;
  }

  /**
   * Get aMFId
   * @return aMFId
   **/
  @JsonProperty(value = "aMFId")
  @ApiModelProperty(value = "")
   @Pattern(regexp="^[A-Fa-f0-9]{6}$")
  public String getaMFId() {
    return aMFId;
  }

  public void setaMFId(String aMFId) {
    this.aMFId = aMFId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServingNetworkFunctionID servingNetworkFunctionID = (ServingNetworkFunctionID) o;
    return Objects.equals(this.servingNetworkFunctionInformation, servingNetworkFunctionID.servingNetworkFunctionInformation) &&
        Objects.equals(this.aMFId, servingNetworkFunctionID.aMFId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(servingNetworkFunctionInformation, aMFId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServingNetworkFunctionID {\n");
    
    sb.append("    servingNetworkFunctionInformation: ").append(toIndentedString(servingNetworkFunctionInformation)).append("\n");
    sb.append("    aMFId: ").append(toIndentedString(aMFId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

