/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ServiceAreaRestriction
 */
@JsonPropertyOrder({
  ServiceAreaRestriction.JSON_PROPERTY_RESTRICTION_TYPE,
  ServiceAreaRestriction.JSON_PROPERTY_AREAS,
  ServiceAreaRestriction.JSON_PROPERTY_MAX_NUM_OF_T_AS,
  ServiceAreaRestriction.JSON_PROPERTY_MAX_NUM_OF_T_AS_FOR_NOT_ALLOWED_AREAS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class ServiceAreaRestriction   {
  public static final String JSON_PROPERTY_RESTRICTION_TYPE = "restrictionType";
  @JsonProperty(JSON_PROPERTY_RESTRICTION_TYPE)
  private RestrictionType restrictionType;

  public static final String JSON_PROPERTY_AREAS = "areas";
  @JsonProperty(JSON_PROPERTY_AREAS)
  private List<@Valid Area> areas;

  public static final String JSON_PROPERTY_MAX_NUM_OF_T_AS = "maxNumOfTAs";
  @JsonProperty(JSON_PROPERTY_MAX_NUM_OF_T_AS)
  private Integer maxNumOfTAs;

  public static final String JSON_PROPERTY_MAX_NUM_OF_T_AS_FOR_NOT_ALLOWED_AREAS = "maxNumOfTAsForNotAllowedAreas";
  @JsonProperty(JSON_PROPERTY_MAX_NUM_OF_T_AS_FOR_NOT_ALLOWED_AREAS)
  private Integer maxNumOfTAsForNotAllowedAreas;

  public ServiceAreaRestriction restrictionType(RestrictionType restrictionType) {
    this.restrictionType = restrictionType;
    return this;
  }

  /**
   * Get restrictionType
   * @return restrictionType
   **/
  @JsonProperty(value = "restrictionType")
  @ApiModelProperty(value = "")
  
  public RestrictionType getRestrictionType() {
    return restrictionType;
  }

  public void setRestrictionType(RestrictionType restrictionType) {
    this.restrictionType = restrictionType;
  }

  public ServiceAreaRestriction areas(List<@Valid Area> areas) {
    this.areas = areas;
    return this;
  }

  public ServiceAreaRestriction addAreasItem(Area areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<>();
    }
    this.areas.add(areasItem);
    return this;
  }

  /**
   * Get areas
   * @return areas
   **/
  @JsonProperty(value = "areas")
  @ApiModelProperty(value = "")
  @Valid 
  public List<@Valid Area> getAreas() {
    return areas;
  }

  public void setAreas(List<@Valid Area> areas) {
    this.areas = areas;
  }

  public ServiceAreaRestriction maxNumOfTAs(Integer maxNumOfTAs) {
    this.maxNumOfTAs = maxNumOfTAs;
    return this;
  }

  /**
   * Get maxNumOfTAs
   * minimum: 0
   * @return maxNumOfTAs
   **/
  @JsonProperty(value = "maxNumOfTAs")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer getMaxNumOfTAs() {
    return maxNumOfTAs;
  }

  public void setMaxNumOfTAs(Integer maxNumOfTAs) {
    this.maxNumOfTAs = maxNumOfTAs;
  }

  public ServiceAreaRestriction maxNumOfTAsForNotAllowedAreas(Integer maxNumOfTAsForNotAllowedAreas) {
    this.maxNumOfTAsForNotAllowedAreas = maxNumOfTAsForNotAllowedAreas;
    return this;
  }

  /**
   * Get maxNumOfTAsForNotAllowedAreas
   * minimum: 0
   * @return maxNumOfTAsForNotAllowedAreas
   **/
  @JsonProperty(value = "maxNumOfTAsForNotAllowedAreas")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer getMaxNumOfTAsForNotAllowedAreas() {
    return maxNumOfTAsForNotAllowedAreas;
  }

  public void setMaxNumOfTAsForNotAllowedAreas(Integer maxNumOfTAsForNotAllowedAreas) {
    this.maxNumOfTAsForNotAllowedAreas = maxNumOfTAsForNotAllowedAreas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAreaRestriction serviceAreaRestriction = (ServiceAreaRestriction) o;
    return Objects.equals(this.restrictionType, serviceAreaRestriction.restrictionType) &&
        Objects.equals(this.areas, serviceAreaRestriction.areas) &&
        Objects.equals(this.maxNumOfTAs, serviceAreaRestriction.maxNumOfTAs) &&
        Objects.equals(this.maxNumOfTAsForNotAllowedAreas, serviceAreaRestriction.maxNumOfTAsForNotAllowedAreas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(restrictionType, areas, maxNumOfTAs, maxNumOfTAsForNotAllowedAreas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAreaRestriction {\n");
    
    sb.append("    restrictionType: ").append(toIndentedString(restrictionType)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("    maxNumOfTAs: ").append(toIndentedString(maxNumOfTAs)).append("\n");
    sb.append("    maxNumOfTAsForNotAllowedAreas: ").append(toIndentedString(maxNumOfTAsForNotAllowedAreas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

