/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.frojasg1.nchf5g.rel16_15_0.openapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SteeringMode
 */
@JsonPropertyOrder({
  SteeringMode.JSON_PROPERTY_STEER_MODE_VALUE,
  SteeringMode.JSON_PROPERTY_ACTIVE,
  SteeringMode.JSON_PROPERTY_STANDBY,
  SteeringMode.JSON_PROPERTY_3G_LOAD,
  SteeringMode.JSON_PROPERTY_PRIO_ACC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2024-09-24T14:40:31.217597300+02:00[Europe/Madrid]", comments = "Generator version: 7.7.0")
public class SteeringMode   {
  public static final String JSON_PROPERTY_STEER_MODE_VALUE = "steerModeValue";
  @JsonProperty(JSON_PROPERTY_STEER_MODE_VALUE)
  private SteerModeValue steerModeValue;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  private AccessType active;

  public static final String JSON_PROPERTY_STANDBY = "standby";
  @JsonProperty(JSON_PROPERTY_STANDBY)
  private AccessType standby;

  public static final String JSON_PROPERTY_3G_LOAD = "3gLoad";
  @JsonProperty(JSON_PROPERTY_3G_LOAD)
  private Integer _3gLoad;

  public static final String JSON_PROPERTY_PRIO_ACC = "prioAcc";
  @JsonProperty(JSON_PROPERTY_PRIO_ACC)
  private AccessType prioAcc;

  public SteeringMode steerModeValue(SteerModeValue steerModeValue) {
    this.steerModeValue = steerModeValue;
    return this;
  }

  /**
   * Get steerModeValue
   * @return steerModeValue
   **/
  @JsonProperty(value = "steerModeValue")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public SteerModeValue getSteerModeValue() {
    return steerModeValue;
  }

  public void setSteerModeValue(SteerModeValue steerModeValue) {
    this.steerModeValue = steerModeValue;
  }

  public SteeringMode active(AccessType active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty(value = "active")
  @ApiModelProperty(value = "")
  
  public AccessType getActive() {
    return active;
  }

  public void setActive(AccessType active) {
    this.active = active;
  }

  public SteeringMode standby(AccessType standby) {
    this.standby = standby;
    return this;
  }

  /**
   * Get standby
   * @return standby
   **/
  @JsonProperty(value = "standby")
  @ApiModelProperty(value = "")
  
  public AccessType getStandby() {
    return standby;
  }

  public void setStandby(AccessType standby) {
    this.standby = standby;
  }

  public SteeringMode _3gLoad(Integer _3gLoad) {
    this._3gLoad = _3gLoad;
    return this;
  }

  /**
   * Get _3gLoad
   * minimum: 0
   * @return _3gLoad
   **/
  @JsonProperty(value = "3gLoad")
  @ApiModelProperty(value = "")
   @Min(0)
  public Integer get3gLoad() {
    return _3gLoad;
  }

  public void set3gLoad(Integer _3gLoad) {
    this._3gLoad = _3gLoad;
  }

  public SteeringMode prioAcc(AccessType prioAcc) {
    this.prioAcc = prioAcc;
    return this;
  }

  /**
   * Get prioAcc
   * @return prioAcc
   **/
  @JsonProperty(value = "prioAcc")
  @ApiModelProperty(value = "")
  
  public AccessType getPrioAcc() {
    return prioAcc;
  }

  public void setPrioAcc(AccessType prioAcc) {
    this.prioAcc = prioAcc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SteeringMode steeringMode = (SteeringMode) o;
    return Objects.equals(this.steerModeValue, steeringMode.steerModeValue) &&
        Objects.equals(this.active, steeringMode.active) &&
        Objects.equals(this.standby, steeringMode.standby) &&
        Objects.equals(this._3gLoad, steeringMode._3gLoad) &&
        Objects.equals(this.prioAcc, steeringMode.prioAcc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(steerModeValue, active, standby, _3gLoad, prioAcc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SteeringMode {\n");
    
    sb.append("    steerModeValue: ").append(toIndentedString(steerModeValue)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    standby: ").append(toIndentedString(standby)).append("\n");
    sb.append("    _3gLoad: ").append(toIndentedString(_3gLoad)).append("\n");
    sb.append("    prioAcc: ").append(toIndentedString(prioAcc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

